import {
  Flame, Coins, Zap, Sparkles, PartyPopper, Trophy, Target, Gift, Gem, Star,
  CheckCircle2, XCircle, Check, X, BookOpen, Book, PencilLine, BarChart3,
  GraduationCap, Map as MapIcon, Brain, ShoppingCart, Users, MessageCircle,
  Handshake, Crown, Medal, Award, Gamepad2, Headphones, Lock, Rocket, Home,
  Smartphone, Dumbbell, Globe, Heart, Lightbulb, Mic, Megaphone, Newspaper,
  ClipboardList, Shirt, PawPrint, Egg, Bird, Cat, Flower2, Sprout, Leaf, Trees,
  Castle, Shield, Sword, Swords, Bot, Sparkle, Moon, Waves, Armchair,
  Footprints, Hospital, Smile, Scissors, Hand, Image as ImageIcon,
  Music, Film, Camera, Calendar, Clock, Mail, Phone, User,
  Bell, Eye, ThumbsUp, AlertTriangle, Info, HelpCircle, Plus, Minus,
  Loader, RefreshCw, Trash2, Edit, Save, Download, Share2,
  Cookie, Cake, Coffee, Apple, Utensils,
  Sun, Cloud, CloudRain, Snowflake, Wind,
  Mountain, Fish, Dog, Rabbit,
  Briefcase, Building, Building2, Wallet,
  Palette, Brush, Tv, Radio,
  Wand2, Puzzle, Dices,
  type LucideIcon,
} from "lucide-react";

/**
 * Centralized emoji → lucide icon mapping.
 * Keys include the original emoji char AND a semantic name so both
 * `<EmojiIcon emoji="🔥" />` and `<EmojiIcon emoji="flame" />` work.
 */
export const EMOJI_ICON_MAP: Record<string, LucideIcon> = {
  // Gamification
  "🔥": Flame, flame: Flame, fire: Flame,
  "🪙": Coins, coin: Coins, coins: Coins,
  "💰": Wallet, money: Wallet,
  "⚡": Zap, zap: Zap, lightning: Zap, energy: Zap,
  "✨": Sparkles, sparkles: Sparkles,
  "💫": Sparkle, sparkle: Sparkle,
  "🌟": Star, "⭐": Star, star: Star, "✦": Star, "✧": Star,
  "🎉": PartyPopper, "🎊": PartyPopper, party: PartyPopper, celebrate: PartyPopper,
  "🏆": Trophy, trophy: Trophy,
  "🎯": Target, target: Target, goal: Target,
  "🎁": Gift, gift: Gift,
  "💎": Gem, gem: Gem,
  "✅": CheckCircle2, check: CheckCircle2,
  "✓": Check, tick: Check,
  "❌": XCircle, cross: XCircle, fail: XCircle,
  "✗": X,
  "❤": Heart, "❤️": Heart, "💕": Heart, "💜": Heart, "💖": Heart, "💗": Heart,
  heart: Heart, love: Heart,

  // Learning content
  "📚": BookOpen, books: BookOpen, library: BookOpen,
  "📖": Book, book: Book, reading: Book,
  "📝": PencilLine, note: PencilLine, write: PencilLine,
  "✏": PencilLine, "✏️": PencilLine, pencil: PencilLine,
  "📊": BarChart3, chart: BarChart3, stats: BarChart3,
  "📋": ClipboardList, clipboard: ClipboardList,
  "📰": Newspaper, news: Newspaper,
  "🎓": GraduationCap, graduation: GraduationCap, school: GraduationCap,
  "🗺": MapIcon, "🗺️": MapIcon, map: MapIcon,
  "🧠": Brain, brain: Brain,
  "💡": Lightbulb, idea: Lightbulb, tip: Lightbulb,
  "🔤": BookOpen, alphabet: BookOpen, abc: BookOpen,

  // Social / shop
  "🛒": ShoppingCart, cart: ShoppingCart, shop: ShoppingCart,
  "👥": Users, users: Users, friends: Users,
  "👤": User, user: User,
  "💬": MessageCircle, chat: MessageCircle, message: MessageCircle,
  "🗣": Megaphone, "🗣️": Megaphone, speak: Megaphone,
  "🎙": Mic, "🎙️": Mic, mic: Mic,
  "🤝": Handshake, handshake: Handshake,
  "👑": Crown, crown: Crown, king: Crown, queen: Crown,
  "🥇": Medal, gold: Medal,
  "🥈": Medal, silver: Medal,
  "🥉": Medal, bronze: Medal,
  "🎖": Award, "🎖️": Award, award: Award,
  "🏅": Medal, medal: Medal,

  // Activities
  "🎮": Gamepad2, "🕹": Gamepad2, "🕹️": Gamepad2, game: Gamepad2, gaming: Gamepad2,
  "🎲": Dices, "🎰": Dices, dice: Dices, slot: Dices,
  "🧩": Puzzle, puzzle: Puzzle,
  "🎧": Headphones, headphones: Headphones, audio: Headphones,
  "🎵": Music, "🎶": Music, music: Music,
  "🎨": Palette, art: Palette,
  "🖌": Brush, "🖌️": Brush, brush: Brush,
  "📺": Tv, tv: Tv,
  "📻": Radio, radio: Radio,
  "🎬": Film, movie: Film, film: Film,
  "📷": Camera, "📸": Camera, camera: Camera,
  "🖼": ImageIcon, "🖼️": ImageIcon, image: ImageIcon,

  // Security / battle
  "🔒": Lock, "🔐": Lock, lock: Lock,
  "🛡": Shield, "🛡️": Shield, shield: Shield,
  "⚔": Swords, "⚔️": Swords, swords: Swords, battle: Swords,
  "🗡": Sword, "🗡️": Sword, sword: Sword,
  "🤖": Bot, robot: Bot, ai: Bot,
  "🪄": Wand2, magic: Wand2,

  // Places
  "🏠": Home, "🏡": Home, home: Home, house: Home,
  "🏰": Castle, castle: Castle,
  "🏥": Hospital, hospital: Hospital,
  "🏢": Building2, office: Building2,
  "🏛": Building, "🏛️": Building, building: Building,
  "🌍": Globe, "🌎": Globe, "🌏": Globe, world: Globe, globe: Globe,
  "🌌": Sparkles, galaxy: Sparkles,
  "🚀": Rocket, rocket: Rocket, launch: Rocket,
  "📱": Smartphone, phone: Smartphone, mobile: Smartphone,
  "💼": Briefcase, briefcase: Briefcase, work: Briefcase,

  // Nature
  "🌱": Sprout, sprout: Sprout, seedling: Sprout,
  "🌿": Leaf, leaf: Leaf, herb: Leaf,
  "🌲": Trees, "🌳": Trees, tree: Trees, forest: Trees,
  "🌸": Flower2, "🌺": Flower2, "🌼": Flower2, "🌻": Flower2, flower: Flower2,
  "🍃": Leaf,
  "🌊": Waves, wave: Waves, water: Waves, ocean: Waves,
  "🌙": Moon, moon: Moon,
  "☀": Sun, "☀️": Sun, sun: Sun,
  "☁": Cloud, "☁️": Cloud, cloud: Cloud,
  "🌧": CloudRain, "🌧️": CloudRain, rain: CloudRain,
  "❄": Snowflake, "❄️": Snowflake, snow: Snowflake,
  "💨": Wind, wind: Wind,
  "⛰": Mountain, "⛰️": Mountain, "🏔": Mountain, "🏔️": Mountain, mountain: Mountain,

  // Animals
  "🐉": Bird, "🐲": Bird, dragon: Bird,
  "🐱": Cat, "🐈": Cat, cat: Cat,
  "🐶": Dog, "🐕": Dog, dog: Dog,
  "🐰": Rabbit, "🐇": Rabbit, rabbit: Rabbit,
  "🐦": Bird, "🐥": Bird, "🐣": Bird, "🦅": Bird, bird: Bird, chick: Bird, eagle: Bird,
  "🐾": PawPrint, paw: PawPrint, pet: PawPrint,
  "🥚": Egg, egg: Egg,
  "🐟": Fish, "🐠": Fish, fish: Fish,

  // Body / character
  "👕": Shirt, shirt: Shirt, clothes: Shirt,
  "👖": Shirt, pants: Shirt,
  "👟": Footprints, shoes: Footprints, sneaker: Footprints,
  "💪": Dumbbell, strong: Dumbbell, strength: Dumbbell,
  "💇": Scissors, "💇‍♀️": Scissors, "💇‍♂️": Scissors, haircut: Scissors,
  "🫲": Hand, hand: Hand,
  "😊": Smile, smile: Smile, happy: Smile,
  "🪑": Armchair, chair: Armchair, furniture: Armchair,
  "🧸": Gift, toy: Gift,
  "🦥": PawPrint, sloth: PawPrint,

  // Food
  "🍕": Cookie, pizza: Cookie,
  "🍪": Cookie, cookie: Cookie,
  "🎂": Cake, "🍰": Cake, cake: Cake,
  "☕": Coffee, coffee: Coffee,
  "🍎": Apple, "🍏": Apple, apple: Apple,
  "🍽": Utensils, "🍽️": Utensils, food: Utensils, eat: Utensils,

  // Meta / system
  "📅": Calendar, calendar: Calendar, date: Calendar,
  "⏰": Clock, "⏲": Clock, "⏲️": Clock, "🕐": Clock, clock: Clock, time: Clock,
  "📧": Mail, "📨": Mail, "✉": Mail, "✉️": Mail, mail: Mail, email: Mail,
  "📞": Phone, telephone: Phone,
  "🔔": Bell, bell: Bell, notification: Bell,
  "👁": Eye, "👁️": Eye, eye: Eye, view: Eye,
  "👍": ThumbsUp, like: ThumbsUp,
  "⚠": AlertTriangle, "⚠️": AlertTriangle, warning: AlertTriangle,
  "ℹ": Info, "ℹ️": Info, info: Info,
  "❓": HelpCircle, "❔": HelpCircle, help: HelpCircle, question: HelpCircle,
  "➕": Plus, plus: Plus, add: Plus,
  "➖": Minus, minus: Minus,
  "🔄": RefreshCw, refresh: RefreshCw,
  "⏳": Loader, "⌛": Loader, loading: Loader,
  "🗑": Trash2, "🗑️": Trash2, trash: Trash2, delete: Trash2,
  "✂": Scissors, "✂️": Scissors,
  "📤": Share2, share: Share2,
  "📥": Download, download: Download,
  "💾": Save, save: Save,
};

/** Convenience: list of every emoji char the map handles (for codemods). */
export const KNOWN_EMOJIS = Object.keys(EMOJI_ICON_MAP);
