import {
  Flame, Coins, Zap, Sparkles, PartyPopper, Trophy, Target, Gift, Gem, Star,
  CheckCircle2, XCircle, Check, X, BookOpen, Book, PencilLine, BarChart3,
  GraduationCap, Map as MapIcon, Brain, ShoppingCart, Users, MessageCircle,
  Handshake, Crown, Medal, Award, Gamepad2, Headphones, Lock, Rocket, Home,
  Smartphone, Dumbbell, Globe, Heart, Lightbulb, Mic, Megaphone, Newspaper,
  ClipboardList, Shirt, PawPrint, Egg, Bird, Cat, Flower2, Sprout, Leaf, Trees,
  Castle, Shield, Sword, Swords, Bot, Eagle, Sparkle, Moon, Waves, Armchair,
  Footprints, Hospital, Smile, CaseSensitive, Scissors, Hand, Image as ImageIcon,
  Music, Film, Camera, Calendar, Clock, MapPin, Mail, Phone, Search, Settings,
  User, UserCheck, UserPlus, UserX, Bell, BellRing, Eye, EyeOff, ThumbsUp,
  ThumbsDown, Pin, Bookmark, Tag, Hash, AlertCircle, AlertTriangle, Info,
  HelpCircle, Plus, Minus, ArrowRight, ArrowLeft, ArrowUp, ArrowDown,
  ChevronRight, ChevronLeft, Loader, RefreshCw, Trash2, Edit, Save, Download,
  Upload, Share2, Link, Copy, ExternalLink, Pizza, Cookie, Cake, Coffee, Apple,
  Wine, Beer, Utensils, Soup, IceCream, Sun, Cloud, CloudRain, Snowflake, Wind,
  Umbrella, Mountain, TreePalm, Bug, Fish, Rabbit, Dog, Squirrel, Turtle, Cog,
  Wrench, Hammer, Briefcase, Building, Building2, Banknote, Wallet, CreditCard,
  Receipt, Diamond, Atom, FlaskConical, Microscope, Telescope, Palette, Brush,
  Drum, Piano, Guitar, Theater, Tv, Radio, Joystick, Dices, Puzzle, Trophy as TrophyIcon,
  Ribbon, Tent, Backpack, Glasses, Compass, Anchor, Plane, Car, Bus, Train, Ship,
  Bike, Battery, Plug, Wifi, Bluetooth, MonitorSmartphone, Laptop, Mouse, Keyboard,
  Volume2, VolumeX, Play, Pause, SkipForward, SkipBack, Repeat, Shuffle,
  Crosshair, Skull, Ghost, Aperture, Wand2, Wand, Snail, Feather, FlameKindling,
  CircleDot, Circle, Square, Triangle, Hexagon,
} from "lucide-react";

import type { LucideIcon } from "lucide-react";

// Centralized emoji → lucide icon mapping.
// Keys include the original emoji char AND a semantic name so data files can use either.
export const EMOJI_ICON_MAP: Record<string, LucideIcon> = {
  // Gamification core
  "🔥": Flame, flame: Flame, fire: Flame,
  "🪙": Coins, coin: Coins, coins: Coins,
  "💰": Wallet, money: Wallet,
  "⚡": Zap, zap: Zap, lightning: Zap, energy: Zap,
  "✨": Sparkles, sparkles: Sparkles, shine: Sparkles,
  "💫": Sparkle, sparkle: Sparkle,
  "🌟": Star, "⭐": Star, star: Star,
  "✦": Star, "✧": Star,
  "🎉": PartyPopper, party: PartyPopper, celebrate: PartyPopper,
  "🎊": PartyPopper,
  "🏆": Trophy, trophy: Trophy, champion: Trophy,
  "🎯": Target, target: Target, goal: Target,
  "🎁": Gift, gift: Gift,
  "💎": Gem, gem: Gem, diamond: Diamond,
  "✅": CheckCircle2, check: CheckCircle2,
  "✓": Check, tick: Check,
  "❌": XCircle, cross: XCircle, fail: XCircle,
  "✗": X,
  "❤": Heart, "❤️": Heart, "💕": Heart, "💜": Heart, "💖": Heart, "💗": Heart,
  heart: Heart, love: Heart,

  // Content / learning
  "📚": BookOpen, books: BookOpen, library: BookOpen,
  "📖": Book, book: Book, reading: Book,
  "📝": PencilLine, note: PencilLine, write: PencilLine, writing: PencilLine,
  "✏": PencilLine, "✏️": PencilLine, pencil: PencilLine,
  "📊": BarChart3, chart: BarChart3, stats: BarChart3,
  "📋": ClipboardList, clipboard: ClipboardList,
  "📰": Newspaper, news: Newspaper,
  "🎓": GraduationCap, graduation: GraduationCap, school: GraduationCap,
  "🗺": MapIcon, "🗺️": MapIcon, map: MapIcon,
  "🧠": Brain, brain: Brain,
  "💡": Lightbulb, idea: Lightbulb, tip: Lightbulb,
  "🔤": CaseSensitive, alphabet: CaseSensitive, abc: CaseSensitive,

  // Social / shop
  "🛒": ShoppingCart, cart: ShoppingCart, shop: ShoppingCart,
  "👥": Users, users: Users, friends: Users,
  "👤": User,
  "💬": MessageCircle, chat: MessageCircle, message: MessageCircle,
  "🗣": Megaphone, "🗣️": Megaphone, speak: Megaphone,
  "🎙": Mic, "🎙️": Mic, mic: Mic,
  "🤝": Handshake, handshake: Handshake,
  "👑": Crown, crown: Crown, king: Crown, queen: Crown,
  "🥇": Medal, gold: Medal,
  "🥈": Medal, silver: Medal,
  "🥉": Medal, bronze: Medal,
  "🎖": Award, "🎖️": Award, award: Award,
  "🏅": Medal, medal: Medal,
  "🎀": Ribbon, ribbon: Ribbon,

  // Activities / tools
  "🎮": Gamepad2, game: Gamepad2, gaming: Gamepad2,
  "🕹": Joystick, "🕹️": Joystick,
  "🎲": Dices, dice: Dices,
  "🎰": Dices, slot: Dices,
  "🧩": Puzzle, puzzle: Puzzle,
  "🎧": Headphones, headphones: Headphones, audio: Headphones,
  "🎵": Music, "🎶": Music, music: Music,
  "🎨": Palette, art: Palette,
  "🖌": Brush, "🖌️": Brush, brush: Brush,
  "🎭": Theater, theater: Theater,
  "📺": Tv, tv: Tv,
  "📻": Radio, radio: Radio,
  "🎬": Film, movie: Film, film: Film,
  "📷": Camera, "📸": Camera, camera: Camera,
  "🖼": ImageIcon, "🖼️": ImageIcon, image: ImageIcon,
  "🥁": Drum, drum: Drum,
  "🎹": Piano, piano: Piano,
  "🎸": Guitar, guitar: Guitar,

  // Security / system
  "🔒": Lock, "🔐": Lock, lock: Lock,
  "🛡": Shield, "🛡️": Shield, shield: Shield,
  "⚔": Swords, "⚔️": Swords, swords: Swords, battle: Swords,
  "🗡": Sword, "🗡️": Sword, sword: Sword,
  "🤖": Bot, robot: Bot, ai: Bot,

  // Places / world
  "🏠": Home, "🏡": Home, home: Home, house: Home,
  "🏰": Castle, castle: Castle,
  "🏥": Hospital, hospital: Hospital,
  "🏢": Building2, office: Building2,
  "🏛": Building, "🏛️": Building, building: Building,
  "⛺": Tent, tent: Tent,
  "🌍": Globe, "🌎": Globe, "🌏": Globe, world: Globe, globe: Globe,
  "🌌": Sparkles, galaxy: Sparkles,
  "🚀": Rocket, rocket: Rocket, launch: Rocket,
  "📱": Smartphone, phone: Smartphone, mobile: Smartphone,
  "💻": Laptop, laptop: Laptop,

  // Nature
  "🌱": Sprout, sprout: Sprout, seedling: Sprout,
  "🌿": Leaf, leaf: Leaf, herb: Leaf,
  "🌲": Trees, "🌳": Trees, tree: Trees, forest: Trees,
  "🌸": Flower2, "🌺": Flower2, "🌼": Flower2, "🌻": Flower2, flower: Flower2,
  "🍃": Leaf,
  "🌊": Waves, wave: Waves, water: Waves, ocean: Waves,
  "🌙": Moon, moon: Moon,
  "☀": Sun, "☀️": Sun, sun: Sun,
  "☁": Cloud, "☁️": Cloud, cloud: Cloud,
  "🌧": CloudRain, "🌧️": CloudRain, rain: CloudRain,
  "❄": Snowflake, "❄️": Snowflake, snow: Snowflake,
  "💨": Wind, wind: Wind,
  "☂": Umbrella, "☂️": Umbrella, "☔": Umbrella, umbrella: Umbrella,
  "⛰": Mountain, "⛰️": Mountain, "🏔": Mountain, "🏔️": Mountain, mountain: Mountain,
  "🌴": TreePalm, palm: TreePalm,

  // Animals
  "🐉": Bird, dragon: Bird, // closest available
  "🐲": Bird,
  "🐱": Cat, "🐈": Cat, cat: Cat,
  "🐶": Dog, "🐕": Dog, dog: Dog,
  "🐰": Rabbit, "🐇": Rabbit, rabbit: Rabbit,
  "🐢": Turtle, turtle: Turtle,
  "🐦": Bird, bird: Bird,
  "🦅": Eagle, eagle: Eagle,
  "🐾": PawPrint, paw: PawPrint, pet: PawPrint,
  "🥚": Egg, egg: Egg,
  