-- Seed: Core A1 Lessons (Level 1)
-- Modules: core-a1-greetings(6), core-a1-numbers(5), core-a1-family(5),
--          core-a1-daily(6), core-a1-food(5), core-a1-places(5),
--          core-a1-shopping(5), core-a1-conversation(6)

SET search_path TO public;

DELETE FROM lessons WHERE module_id LIKE 'core-a1-%';

INSERT INTO lessons (level, lesson_order, title, title_thai, vocabulary, article_sentences, article_translation, image_prompt, quiz, is_published, module_id, topic)
VALUES

-- ==========================================
-- Module: core-a1-greetings (6 lessons)
-- ==========================================

-- Lesson 1
(1, 1, 'Hello! How Are You?', 'สวัสดี! เป็นยังไงบ้าง?',
$$[{"word":"hello","phonetic":"เฮลโล","meaning":"สวัสดี","partOfSpeech":"interj."},{"word":"how are you","phonetic":"ฮาว อาร์ ยู","meaning":"เป็นยังไงบ้าง","partOfSpeech":"phr."},{"word":"fine","phonetic":"ไฟน์","meaning":"ดี / โอเค","partOfSpeech":"adj."},{"word":"thank you","phonetic":"แธงค์ยู","meaning":"ขอบคุณ","partOfSpeech":"phr."},{"word":"and you","phonetic":"แอนด์ ยู","meaning":"แล้วคุณล่ะ","partOfSpeech":"phr."},{"word":"great","phonetic":"เกรท","meaning":"ดีมาก","partOfSpeech":"adj."}]$$::jsonb,
$$[[{"english":"Hello!","thai":"เฮลโล!"},{"english":"My","thai":"มาย"},{"english":"name","thai":"เนม"},{"english":"is","thai":"อิส"},{"english":"Tom.","thai":"ทอม"}],[{"english":"How","thai":"ฮาว"},{"english":"are","thai":"อาร์"},{"english":"you?","thai":"ยู?"}],[{"english":"I","thai":"ไอ"},{"english":"am","thai":"แอม"},{"english":"fine,","thai":"ไฟน์,"},{"english":"thank","thai":"แธงค์"},{"english":"you.","thai":"ยู"}],[{"english":"And","thai":"แอนด์"},{"english":"you?","thai":"ยู?"}],[{"english":"I","thai":"ไอ"},{"english":"am","thai":"แอม"},{"english":"great!","thai":"เกรท!"}]]$$::jsonb,
'สวัสดี! ฉันชื่อทอม เป็นยังไงบ้าง? ฉันดี ขอบคุณ แล้วคุณล่ะ? ฉันดีมาก!',
'Two cartoon students greeting each other at school, bright and friendly atmosphere',
$$[{"question":"\"How are you?\" แปลว่าอะไร?","options":["ชื่ออะไร","เป็นยังไงบ้าง","อยู่ที่ไหน","ทำอะไร"],"correctIndex":1,"type":"vocab"},{"question":"\"Fine\" แปลว่าอะไร?","options":["แย่","ดี","เหนื่อย","หิว"],"correctIndex":1,"type":"vocab"},{"question":"ทอมตอบว่าอะไรเมื่อถูกถาม How are you?","options":["Hello","Great","Fine, thank you","And you?"],"correctIndex":2,"type":"comprehension"},{"question":"\"Great\" แปลว่าอะไร?","options":["โอเค","แย่","ดีมาก","พอใช้"],"correctIndex":2,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-greetings', 'Basic Greetings'),

-- Lesson 2
(1, 2, 'What Is Your Name?', 'ชื่ออะไร?',
$$[{"word":"name","phonetic":"เนม","meaning":"ชื่อ","partOfSpeech":"n."},{"word":"my name is","phonetic":"มาย เนม อิส","meaning":"ฉันชื่อ","partOfSpeech":"phr."},{"word":"what","phonetic":"ว็อท","meaning":"อะไร","partOfSpeech":"pron."},{"word":"your","phonetic":"ยัวร์","meaning":"ของคุณ","partOfSpeech":"pron."},{"word":"nice to meet you","phonetic":"ไนซ์ ทู มีท ยู","meaning":"ยินดีที่ได้รู้จัก","partOfSpeech":"phr."},{"word":"too","phonetic":"ทู","meaning":"เช่นกัน","partOfSpeech":"adv."}]$$::jsonb,
$$[[{"english":"\"What","thai":"\"ว็อท"},{"english":"is","thai":"อิส"},{"english":"your","thai":"ยัวร์"},{"english":"name?\"","thai":"เนม?\""}],[{"english":"\"My","thai":"\"มาย"},{"english":"name","thai":"เนม"},{"english":"is","thai":"อิส"},{"english":"Amy.\"","thai":"เอมี่\""}],[{"english":"\"Nice","thai":"\"ไนซ์"},{"english":"to","thai":"ทู"},{"english":"meet","thai":"มีท"},{"english":"you!\"","thai":"ยู!\""}],[{"english":"\"Nice","thai":"\"ไนซ์"},{"english":"to","thai":"ทู"},{"english":"meet","thai":"มีท"},{"english":"you","thai":"ยู"},{"english":"too!\"","thai":"ทู!\""}]]$$::jsonb,
'"ชื่ออะไร?" "ฉันชื่อเอมี่" "ยินดีที่ได้รู้จัก!" "ยินดีที่ได้รู้จักเช่นกัน!"',
'Two children introducing themselves, shaking hands, school setting, cartoon style',
$$[{"question":"\"My name is\" แปลว่าอะไร?","options":["ชื่อของคุณ","ฉันชื่อ","ชื่อเขา","ชื่อเธอ"],"correctIndex":1,"type":"vocab"},{"question":"\"Nice to meet you\" แปลว่าอะไร?","options":["ลาก่อน","ขอบคุณ","ยินดีที่ได้รู้จัก","สวัสดี"],"correctIndex":2,"type":"vocab"},{"question":"เด็กผู้หญิงชื่ออะไร?","options":["Tom","Amy","Sam","Ann"],"correctIndex":1,"type":"comprehension"},{"question":"\"Too\" แปลว่าอะไร?","options":["มาก","เช่นกัน","แต่","และ"],"correctIndex":1,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-greetings', 'Introductions'),

-- Lesson 3
(1, 3, 'Good Morning, Good Evening', 'สวัสดีตอนเช้า ตอนเย็น',
$$[{"word":"good morning","phonetic":"กู๊ด มอร์นิง","meaning":"สวัสดีตอนเช้า","partOfSpeech":"phr."},{"word":"good afternoon","phonetic":"กู๊ด อาฟเตอร์นูน","meaning":"สวัสดีตอนบ่าย","partOfSpeech":"phr."},{"word":"good evening","phonetic":"กู๊ด อีฟนิง","meaning":"สวัสดีตอนเย็น","partOfSpeech":"phr."},{"word":"good night","phonetic":"กู๊ด ไนท์","meaning":"ราตรีสวัสดิ์","partOfSpeech":"phr."},{"word":"teacher","phonetic":"ทีเชอร์","meaning":"ครู","partOfSpeech":"n."},{"word":"class","phonetic":"คลาส","meaning":"ชั้นเรียน","partOfSpeech":"n."}]$$::jsonb,
$$[[{"english":"Good","thai":"กู๊ด"},{"english":"morning,","thai":"มอร์นิง,"},{"english":"class!","thai":"คลาส!"}],[{"english":"Good","thai":"กู๊ด"},{"english":"morning,","thai":"มอร์นิง,"},{"english":"teacher!","thai":"ทีเชอร์!"}],[{"english":"Good","thai":"กู๊ด"},{"english":"afternoon,","thai":"อาฟเตอร์นูน,"},{"english":"everyone.","thai":"เอฟรีวัน"}],[{"english":"Good","thai":"กู๊ด"},{"english":"evening!","thai":"อีฟนิง!"},{"english":"How","thai":"ฮาว"},{"english":"was","thai":"วอส"},{"english":"your","thai":"ยัวร์"},{"english":"day?","thai":"เดย์?"}],[{"english":"Good","thai":"กู๊ด"},{"english":"night!","thai":"ไนท์!"},{"english":"Sleep","thai":"สลีป"},{"english":"well.","thai":"เวล"}]]$$::jsonb,
'สวัสดีตอนเช้าชั้นเรียน! สวัสดีตอนเช้าครู! สวัสดีตอนบ่ายทุกคน สวัสดีตอนเย็น! วันนี้เป็นยังไงบ้าง? ราตรีสวัสดิ์! นอนหลับฝันดี',
'Classroom scene showing different times of day, teacher and students greeting, cartoon style',
$$[{"question":"\"Good afternoon\" แปลว่าอะไร?","options":["สวัสดีตอนเช้า","สวัสดีตอนบ่าย","สวัสดีตอนเย็น","ราตรีสวัสดิ์"],"correctIndex":1,"type":"vocab"},{"question":"\"Teacher\" แปลว่าอะไร?","options":["นักเรียน","เพื่อน","ครู","พ่อแม่"],"correctIndex":2,"type":"vocab"},{"question":"ครูพูดว่าอะไรกับชั้นเรียนตอนเช้า?","options":["Good night","Good evening","Good morning","Good afternoon"],"correctIndex":2,"type":"comprehension"},{"question":"\"Good night\" ใช้เมื่อไหร่?","options":["ตอนเช้า","ตอนบ่าย","ตอนเย็น","ก่อนนอน"],"correctIndex":3,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-greetings', 'Time Greetings'),

-- Lesson 4
(1, 4, 'Where Are You From?', 'คุณมาจากไหน?',
$$[{"word":"where","phonetic":"แวร์","meaning":"ที่ไหน","partOfSpeech":"adv."},{"word":"from","phonetic":"ฟรอม","meaning":"จาก","partOfSpeech":"prep."},{"word":"I am from","phonetic":"ไอ แอม ฟรอม","meaning":"ฉันมาจาก","partOfSpeech":"phr."},{"word":"Thailand","phonetic":"ไทแลนด์","meaning":"ประเทศไทย","partOfSpeech":"n."},{"word":"country","phonetic":"คันทรี","meaning":"ประเทศ","partOfSpeech":"n."},{"word":"live","phonetic":"ลิฟ","meaning":"อาศัยอยู่","partOfSpeech":"v."}]$$::jsonb,
$$[[{"english":"\"Where","thai":"\"แวร์"},{"english":"are","thai":"อาร์"},{"english":"you","thai":"ยู"},{"english":"from?\"","thai":"ฟรอม?\""}],[{"english":"\"I","thai":"\"ไอ"},{"english":"am","thai":"แอม"},{"english":"from","thai":"ฟรอม"},{"english":"Thailand.\"","thai":"ไทแลนด์\""}],[{"english":"\"I","thai":"\"ไอ"},{"english":"live","thai":"ลิฟ"},{"english":"in","thai":"อิน"},{"english":"Bangkok.\"","thai":"แบงค็อก\""}],[{"english":"\"What","thai":"\"ว็อท"},{"english":"country","thai":"คันทรี"},{"english":"are","thai":"อาร์"},{"english":"you","thai":"ยู"},{"english":"from?\"","thai":"ฟรอม?\""}],[{"english":"\"I","thai":"\"ไอ"},{"english":"am","thai":"แอม"},{"english":"from","thai":"ฟรอม"},{"english":"Japan.\"","thai":"เจแปน\""}]]$$::jsonb,
'"คุณมาจากไหน?" "ฉันมาจากประเทศไทย" "ฉันอาศัยอยู่ที่กรุงเทพ" "คุณมาจากประเทศอะไร?" "ฉันมาจากญี่ปุ่น"',
'Two students from different countries talking, world map in background, cartoon style',
$$[{"question":"\"Where are you from?\" แปลว่าอะไร?","options":["คุณชื่ออะไร","คุณอายุเท่าไหร่","คุณมาจากไหน","คุณอยู่ที่ไหน"],"correctIndex":2,"type":"vocab"},{"question":"\"Country\" แปลว่าอะไร?","options":["เมือง","ประเทศ","หมู่บ้าน","ทวีป"],"correctIndex":1,"type":"vocab"},{"question":"เด็กคนแรกมาจากที่ไหน?","options":["Japan","China","Thailand","Korea"],"correctIndex":2,"type":"comprehension"},{"question":"\"Live\" แปลว่าอะไร?","options":["ทำงาน","เรียน","อาศัยอยู่","เดินทาง"],"correctIndex":2,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-greetings', 'Where Are You From'),

-- Lesson 5
(1, 5, 'How Old Are You?', 'คุณอายุเท่าไหร่?',
$$[{"word":"how old","phonetic":"ฮาว โอลด์","meaning":"อายุเท่าไหร่","partOfSpeech":"phr."},{"word":"years old","phonetic":"เยียร์ส โอลด์","meaning":"ขวบ / ปี","partOfSpeech":"phr."},{"word":"I am ... years old","phonetic":"ไอ แอม ... เยียร์ส โอลด์","meaning":"ฉันอายุ ... ปี","partOfSpeech":"phr."},{"word":"birthday","phonetic":"เบิร์ธเดย์","meaning":"วันเกิด","partOfSpeech":"n."},{"word":"when","phonetic":"เวน","meaning":"เมื่อไหร่","partOfSpeech":"adv."},{"word":"month","phonetic":"มันธ์","meaning":"เดือน","partOfSpeech":"n."}]$$::jsonb,
$$[[{"english":"\"How","thai":"\"ฮาว"},{"english":"old","thai":"โอลด์"},{"english":"are","thai":"อาร์"},{"english":"you?\"","thai":"ยู?\""}],[{"english":"\"I","thai":"\"ไอ"},{"english":"am","thai":"แอม"},{"english":"twelve","thai":"ทเวลฟ์"},{"english":"years","thai":"เยียร์ส"},{"english":"old.\"","thai":"โอลด์\""}],[{"english":"\"When","thai":"\"เวน"},{"english":"is","thai":"อิส"},{"english":"your","thai":"ยัวร์"},{"english":"birthday?\"","thai":"เบิร์ธเดย์?\""}],[{"english":"\"My","thai":"\"มาย"},{"english":"birthday","thai":"เบิร์ธเดย์"},{"english":"is","thai":"อิส"},{"english":"in","thai":"อิน"},{"english":"July.\"","thai":"จูไลย์\""}]]$$::jsonb,
'"คุณอายุเท่าไหร่?" "ฉันอายุสิบสองปี" "วันเกิดของคุณเมื่อไหร่?" "วันเกิดของฉันอยู่ในเดือนกรกฎาคม"',
'Two kids talking about age and birthday, birthday cake in background, cartoon style',
$$[{"question":"\"How old are you?\" แปลว่าอะไร?","options":["คุณชื่ออะไร","คุณอายุเท่าไหร่","คุณมาจากไหน","คุณอยู่ที่ไหน"],"correctIndex":1,"type":"vocab"},{"question":"\"Birthday\" แปลว่าอะไร?","options":["วันหยุด","วันเกิด","วันครบรอบ","วันสำคัญ"],"correctIndex":1,"type":"vocab"},{"question":"เด็กอายุเท่าไหร่?","options":["ten","eleven","twelve","thirteen"],"correctIndex":2,"type":"comprehension"},{"question":"วันเกิดอยู่ในเดือนอะไร?","options":["June","July","August","September"],"correctIndex":1,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-greetings', 'Age and Birthday'),

-- Lesson 6
(1, 6, 'Goodbye! See You Later!', 'ลาก่อน! แล้วเจอกัน!',
$$[{"word":"goodbye","phonetic":"กู๊ดบาย","meaning":"ลาก่อน","partOfSpeech":"interj."},{"word":"see you later","phonetic":"ซี ยู เลเตอร์","meaning":"แล้วเจอกัน","partOfSpeech":"phr."},{"word":"see you tomorrow","phonetic":"ซี ยู ทูมอร์โรว์","meaning":"แล้วเจอกันพรุ่งนี้","partOfSpeech":"phr."},{"word":"take care","phonetic":"เทค แคร์","meaning":"ดูแลตัวเองด้วย","partOfSpeech":"phr."},{"word":"have a good day","phonetic":"แฮฟ อะ กู๊ด เดย์","meaning":"ขอให้มีวันที่ดี","partOfSpeech":"phr."},{"word":"you too","phonetic":"ยู ทู","meaning":"คุณเช่นกัน","partOfSpeech":"phr."}]$$::jsonb,
$$[[{"english":"\"Goodbye,","thai":"\"กู๊ดบาย,"},{"english":"Tom!\"","thai":"ทอม!\""}],[{"english":"\"See","thai":"\"ซี"},{"english":"you","thai":"ยู"},{"english":"tomorrow!\"","thai":"ทูมอร์โรว์!\""}],[{"english":"\"Have","thai":"\"แฮฟ"},{"english":"a","thai":"อะ"},{"english":"good","thai":"กู๊ด"},{"english":"day!\"","thai":"เดย์!\""}],[{"english":"\"You","thai":"\"ยู"},{"english":"too!","thai":"ทู!"},{"english":"Take","thai":"เทค"},{"english":"care!\"","thai":"แคร์!\""}]]$$::jsonb,
'"ลาก่อน ทอม!" "แล้วเจอกันพรุ่งนี้!" "ขอให้มีวันที่ดี!" "คุณเช่นกัน! ดูแลตัวเองด้วย!"',
'Two students waving goodbye at school gate, afternoon setting, cartoon style',
$$[{"question":"\"Goodbye\" แปลว่าอะไร?","options":["สวัสดี","ขอบคุณ","ลาก่อน","ยินดีที่ได้รู้จัก"],"correctIndex":2,"type":"vocab"},{"question":"\"Take care\" แปลว่าอะไร?","options":["ขอบคุณ","ลาก่อน","ดูแลตัวเองด้วย","แล้วเจอกัน"],"correctIndex":2,"type":"vocab"},{"question":"\"See you tomorrow\" แปลว่าอะไร?","options":["แล้วเจอกันภายหลัง","แล้วเจอกันพรุ่งนี้","แล้วเจอกันสัปดาห์หน้า","ลาก่อน"],"correctIndex":1,"type":"comprehension"},{"question":"\"Have a good day\" แปลว่าอะไร?","options":["ราตรีสวัสดิ์","ดูแลตัวเองด้วย","ขอให้มีวันที่ดี","แล้วเจอกัน"],"correctIndex":2,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-greetings', 'Saying Goodbye'),

-- ==========================================
-- Module: core-a1-numbers (5 lessons)
-- ==========================================

-- Lesson 1
(1, 1, 'Counting to 100', 'นับถึงร้อย',
$$[{"word":"thirty","phonetic":"เธอร์ตี","meaning":"สามสิบ","partOfSpeech":"number"},{"word":"forty","phonetic":"ฟอร์ตี","meaning":"สี่สิบ","partOfSpeech":"number"},{"word":"fifty","phonetic":"ฟิฟตี","meaning":"ห้าสิบ","partOfSpeech":"number"},{"word":"hundred","phonetic":"ฮันเดรด","meaning":"ร้อย","partOfSpeech":"number"},{"word":"count","phonetic":"เคานท์","meaning":"นับ","partOfSpeech":"v."},{"word":"number","phonetic":"นัมเบอร์","meaning":"ตัวเลข","partOfSpeech":"n."}]$$::jsonb,
$$[[{"english":"Let","thai":"เลท"},{"english":"us","thai":"อัส"},{"english":"count","thai":"เคานท์"},{"english":"together.","thai":"ทูเกเธอร์"}],[{"english":"Ten,","thai":"เทน,"},{"english":"twenty,","thai":"ทเวนตี,"},{"english":"thirty,","thai":"เธอร์ตี,"},{"english":"forty.","thai":"ฟอร์ตี"}],[{"english":"Fifty,","thai":"ฟิฟตี,"},{"english":"sixty,","thai":"ซิกซ์ตี,"},{"english":"seventy,","thai":"เซเวนตี,"},{"english":"eighty.","thai":"เอทตี"}],[{"english":"Ninety,","thai":"ไนน์ตี,"},{"english":"one","thai":"วัน"},{"english":"hundred!","thai":"ฮันเดรด!"}]]$$::jsonb,
'มาร่วมกันนับ สิบ ยี่สิบ สามสิบ สี่สิบ ห้าสิบ หกสิบ เจ็ดสิบ แปดสิบ เก้าสิบ หนึ่งร้อย!',
'Cartoon children counting numbers on a big board, colorful classroom setting',
$$[{"question":"\"Fifty\" แปลว่าอะไร?","options":["สี่สิบ","ห้าสิบ","หกสิบ","เจ็ดสิบ"],"correctIndex":1,"type":"vocab"},{"question":"\"Hundred\" แปลว่าอะไร?","options":["สิบ","ยี่สิบ","ร้อย","พัน"],"correctIndex":2,"type":"vocab"},{"question":"หลังจาก ninety มาอะไร?","options":["eighty","seventy","one hundred","sixty"],"correctIndex":2,"type":"comprehension"},{"question":"\"Count\" แปลว่าอะไร?","options":["บวก","ลบ","นับ","คูณ"],"correctIndex":2,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-numbers', 'Counting to 100'),

-- Lesson 2
(1, 2, 'How Much Does It Cost?', 'ราคาเท่าไหร่?',
$$[{"word":"how much","phonetic":"ฮาว มัช","meaning":"เท่าไหร่","partOfSpeech":"phr."},{"word":"price","phonetic":"ไพรซ์","meaning":"ราคา","partOfSpeech":"n."},{"word":"baht","phonetic":"บาท","meaning":"บาท","partOfSpeech":"n."},{"word":"dollar","phonetic":"ดอลลาร์","meaning":"ดอลลาร์","partOfSpeech":"n."},{"word":"cheap","phonetic":"ชีพ","meaning":"ถูก","partOfSpeech":"adj."},{"word":"expensive","phonetic":"อิกซ์เพนซิฟ","meaning":"แพง","partOfSpeech":"adj."}]$$::jsonb,
$$[[{"english":"\"How","thai":"\"ฮาว"},{"english":"much","thai":"มัช"},{"english":"is","thai":"อิส"},{"english":"this?\"","thai":"ดิส?\""}],[{"english":"\"It","thai":"\"อิท"},{"english":"is","thai":"อิส"},{"english":"fifty","thai":"ฟิฟตี"},{"english":"baht.\"","thai":"บาท\""}],[{"english":"\"That","thai":"\"แดท"},{"english":"is","thai":"อิส"},{"english":"cheap!\"","thai":"ชีพ!\""}],[{"english":"\"This","thai":"\"ดิส"},{"english":"bag","thai":"แบก"},{"english":"is","thai":"อิส"},{"english":"five","thai":"ไฟว์"},{"english":"hundred","thai":"ฮันเดรด"},{"english":"baht.","thai":"บาท"},{"english":"It","thai":"อิท"},{"english":"is","thai":"อิส"},{"english":"expensive.\"","thai":"อิกซ์เพนซิฟ\""}]]$$::jsonb,
'"ราคาเท่าไหร่?" "ห้าสิบบาท" "ถูกมาก!" "กระเป๋าใบนี้ห้าร้อยบาท มันแพง"',
'Market scene with price tags, cartoon style, colorful Thai market',
$$[{"question":"\"How much?\" แปลว่าอะไร?","options":["กี่ชิ้น","เท่าไหร่","อะไร","ที่ไหน"],"correctIndex":1,"type":"vocab"},{"question":"\"Expensive\" แปลว่าอะไร?","options":["ถูก","ฟรี","แพง","ลดราคา"],"correctIndex":2,"type":"vocab"},{"question":"ของชิ้นแรกราคาเท่าไหร่?","options":["30 baht","50 baht","100 baht","500 baht"],"correctIndex":1,"type":"comprehension"},{"question":"กระเป๋าราคาเท่าไหร่?","options":["50 baht","100 baht","500 baht","1000 baht"],"correctIndex":2,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-numbers', 'Prices and Money'),

-- Lesson 3
(1, 3, 'What Time Is It?', 'กี่โมงแล้ว?',
$$[{"word":"what time","phonetic":"ว็อท ไทม์","meaning":"กี่โมง","partOfSpeech":"phr."},{"word":"o''clock","phonetic":"โอคล็อค","meaning":"นาฬิกา (ตรง)","partOfSpeech":"phr."},{"word":"half past","phonetic":"ฮาฟ พาสท์","meaning":"ครึ่ง (30 นาที)","partOfSpeech":"phr."},{"word":"morning","phonetic":"มอร์นิง","meaning":"ตอนเช้า","partOfSpeech":"n."},{"word":"afternoon","phonetic":"อาฟเตอร์นูน","meaning":"ตอนบ่าย","partOfSpeech":"n."},{"word":"evening","phonetic":"อีฟนิง","meaning":"ตอนเย็น","partOfSpeech":"n."}]$$::jsonb,
$$[[{"english":"\"What","thai":"\"ว็อท"},{"english":"time","thai":"ไทม์"},{"english":"is","thai":"อิส"},{"english":"it?\"","thai":"อิท?\""}],[{"english":"\"It","thai":"\"อิท"},{"english":"is","thai":"อิส"},{"english":"eight","thai":"เอท"},{"english":"o''clock","thai":"โอคล็อค"},{"english":"in","thai":"อิน"},{"english":"the","thai":"เดอะ"},{"english":"morning.\"","thai":"มอร์นิง\""}],[{"english":"School","thai":"สคูล"},{"english":"starts","thai":"สตาร์ทส์"},{"english":"at","thai":"แอท"},{"english":"eight","thai":"เอท"},{"english":"thirty.","thai":"เธอร์ตี"}],[{"english":"Lunch","thai":"ลันช์"},{"english":"is","thai":"อิส"},{"english":"at","thai":"แอท"},{"english":"twelve","thai":"ทเวลฟ์"},{"english":"o''clock.","thai":"โอคล็อค"}]]$$::jsonb,
'"กี่โมงแล้ว?" "แปดโมงเช้า" โรงเรียนเริ่มแปดโมงครึ่ง อาหารกลางวันตอนเที่ยงตรง',
'Clock showing different times, school schedule, cartoon style',
$$[{"question":"\"What time is it?\" แปลว่าอะไร?","options":["วันนี้วันอะไร","กี่โมงแล้ว","อยู่ที่ไหน","ทำอะไร"],"correctIndex":1,"type":"vocab"},{"question":"\"Morning\" แปลว่าอะไร?","options":["ตอนเย็น","ตอนกลางคืน","ตอนเช้า","ตอนบ่าย"],"correctIndex":2,"type":"vocab"},{"question":"โรงเรียนเริ่มกี่โมง?","options":["7:00","7:30","8:00","8:30"],"correctIndex":3,"type":"comprehension"},{"question":"อาหารกลางวันกี่โมง?","options":["11:00","11:30","12:00","12:30"],"correctIndex":2,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-numbers', 'Telling Time'),

-- Lesson 4
(1, 4, 'Days of the Week', 'วันในสัปดาห์',
$$[{"word":"Monday","phonetic":"มันเดย์","meaning":"วันจันทร์","partOfSpeech":"n."},{"word":"Wednesday","phonetic":"เวนส์เดย์","meaning":"วันพุธ","partOfSpeech":"n."},{"word":"Friday","phonetic":"ไฟรเดย์","meaning":"วันศุกร์","partOfSpeech":"n."},{"word":"weekend","phonetic":"วีคเอนด์","meaning":"วันหยุดสุดสัปดาห์","partOfSpeech":"n."},{"word":"today","phonetic":"ทูเดย์","meaning":"วันนี้","partOfSpeech":"n."},{"word":"tomorrow","phonetic":"ทูมอร์โรว์","meaning":"พรุ่งนี้","partOfSpeech":"n."}]$$::jsonb,
$$[[{"english":"Today","thai":"ทูเดย์"},{"english":"is","thai":"อิส"},{"english":"Monday.","thai":"มันเดย์"}],[{"english":"Tomorrow","thai":"ทูมอร์โรว์"},{"english":"is","thai":"อิส"},{"english":"Tuesday.","thai":"ทิวส์เดย์"}],[{"english":"I","thai":"ไอ"},{"english":"like","thai":"ไลค์"},{"english":"Friday","thai":"ไฟรเดย์"},{"english":"because","thai":"บีคอส"},{"english":"it","thai":"อิท"},{"english":"is","thai":"อิส"},{"english":"the","thai":"เดอะ"},{"english":"weekend!","thai":"วีคเอนด์!"}],[{"english":"Saturday","thai":"แซทเทอร์เดย์"},{"english":"and","thai":"แอนด์"},{"english":"Sunday","thai":"ซันเดย์"},{"english":"are","thai":"อาร์"},{"english":"my","thai":"มาย"},{"english":"favorite","thai":"เฟเวอริท"},{"english":"days.","thai":"เดย์ส"}]]$$::jsonb,
'วันนี้วันจันทร์ พรุ่งนี้วันอังคาร ฉันชอบวันศุกร์เพราะเป็นวันหยุดสุดสัปดาห์! วันเสาร์และวันอาทิตย์เป็นวันที่ฉันชอบที่สุด',
'Weekly calendar with cartoon activities for each day, colorful and fun',
$$[{"question":"\"Monday\" แปลว่าอะไร?","options":["วันอาทิตย์","วันจันทร์","วันอังคาร","วันพุธ"],"correctIndex":1,"type":"vocab"},{"question":"\"Weekend\" แปลว่าอะไร?","options":["วันธรรมดา","วันหยุดสุดสัปดาห์","วันหยุดนักขัตฤกษ์","วันเกิด"],"correctIndex":1,"type":"vocab"},{"question":"วันนี้วันอะไร?","options":["Sunday","Monday","Tuesday","Wednesday"],"correctIndex":1,"type":"comprehension"},{"question":"วันหยุดสุดสัปดาห์คือวันอะไรบ้าง?","options":["Mon-Tue","Fri-Sat","Sat-Sun","Thu-Fri"],"correctIndex":2,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-numbers', 'Days of the Week'),

-- Lesson 5
(1, 5, 'Months and Seasons', 'เดือนและฤดูกาล',
$$[{"word":"January","phonetic":"แจนนิวแอรี","meaning":"มกราคม","partOfSpeech":"n."},{"word":"month","phonetic":"มันธ์","meaning":"เดือน","partOfSpeech":"n."},{"word":"season","phonetic":"ซีซัน","meaning":"ฤดูกาล","partOfSpeech":"n."},{"word":"summer","phonetic":"ซัมเมอร์","meaning":"ฤดูร้อน","partOfSpeech":"n."},{"word":"winter","phonetic":"วินเตอร์","meaning":"ฤดูหนาว","partOfSpeech":"n."},{"word":"year","phonetic":"เยียร์","meaning":"ปี","partOfSpeech":"n."}]$$::jsonb,
$$[[{"english":"There","thai":"แดร์"},{"english":"are","thai":"อาร์"},{"english":"twelve","thai":"ทเวลฟ์"},{"english":"months","thai":"มันธ์ส"},{"english":"in","thai":"อิน"},{"english":"a","thai":"อะ"},{"english":"year.","thai":"เยียร์"}],[{"english":"January","thai":"แจนนิวแอรี"},{"english":"is","thai":"อิส"},{"english":"the","thai":"เดอะ"},{"english":"first","thai":"เฟิร์สท์"},{"english":"month.","thai":"มันธ์"}],[{"english":"Summer","thai":"ซัมเมอร์"},{"english":"is","thai":"อิส"},{"english":"hot","thai":"ฮ็อท"},{"english":"and","thai":"แอนด์"},{"english":"sunny.","thai":"ซันนี"}],[{"english":"Winter","thai":"วินเตอร์"},{"english":"is","thai":"อิส"},{"english":"cold","thai":"โคลด์"},{"english":"and","thai":"แอนด์"},{"english":"snowy.","thai":"สโนวี"}]]$$::jsonb,
'ในหนึ่งปีมีสิบสองเดือน มกราคมเป็นเดือนแรก ฤดูร้อนร้อนและมีแดด ฤดูหนาวหนาวและมีหิมะ',
'Four seasons shown in cartoon panels, colorful nature scenes',
$$[{"question":"\"Season\" แปลว่าอะไร?","options":["เดือน","ปี","ฤดูกาล","สัปดาห์"],"correctIndex":2,"type":"vocab"},{"question":"\"Winter\" แปลว่าอะไร?","options":["ฤดูร้อน","ฤดูใบไม้ร่วง","ฤดูหนาว","ฤดูใบไม้ผลิ"],"correctIndex":2,"type":"vocab"},{"question":"ในหนึ่งปีมีกี่เดือน?","options":["ten","eleven","twelve","thirteen"],"correctIndex":2,"type":"comprehension"},{"question":"ฤดูร้อนเป็นยังไง?","options":["cold and snowy","hot and sunny","windy and rainy","cool and cloudy"],"correctIndex":1,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-numbers', 'Months and Seasons'),

-- ==========================================
-- Module: core-a1-family (5 lessons)
-- ==========================================

-- Lesson 1
(1, 1, 'My Family', 'ครอบครัวของฉัน',
$$[{"word":"family","phonetic":"แฟมิลี","meaning":"ครอบครัว","partOfSpeech":"n."},{"word":"mother","phonetic":"มาเธอร์","meaning":"แม่","partOfSpeech":"n."},{"word":"father","phonetic":"ฟาเธอร์","meaning":"พ่อ","partOfSpeech":"n."},{"word":"sister","phonetic":"ซิสเตอร์","meaning":"พี่สาว/น้องสาว","partOfSpeech":"n."},{"word":"brother","phonetic":"บราเธอร์","meaning":"พี่ชาย/น้องชาย","partOfSpeech":"n."},{"word":"love","phonetic":"ลัฟ","meaning":"รัก","partOfSpeech":"v."}]$$::jsonb,
$$[[{"english":"This","thai":"ดิส"},{"english":"is","thai":"อิส"},{"english":"my","thai":"มาย"},{"english":"family.","thai":"แฟมิลี"}],[{"english":"My","thai":"มาย"},{"english":"mother","thai":"มาเธอร์"},{"english":"is","thai":"อิส"},{"english":"kind.","thai":"ไคนด์"}],[{"english":"My","thai":"มาย"},{"english":"father","thai":"ฟาเธอร์"},{"english":"is","thai":"อิส"},{"english":"tall.","thai":"ทอล"}],[{"english":"I","thai":"ไอ"},{"english":"have","thai":"แฮฟ"},{"english":"one","thai":"วัน"},{"english":"sister","thai":"ซิสเตอร์"},{"english":"and","thai":"แอนด์"},{"english":"one","thai":"วัน"},{"english":"brother.","thai":"บราเธอร์"}],[{"english":"I","thai":"ไอ"},{"english":"love","thai":"ลัฟ"},{"english":"my","thai":"มาย"},{"english":"family!","thai":"แฟมิลี!"}]]$$::jsonb,
'นี่คือครอบครัวของฉัน แม่ของฉันใจดี พ่อของฉันสูง ฉันมีพี่สาวหนึ่งคนและพี่ชายหนึ่งคน ฉันรักครอบครัวของฉัน!',
'Happy cartoon family portrait with parents and two children, warm home setting',
$$[{"question":"\"Mother\" แปลว่าอะไร?","options":["พ่อ","แม่","พี่สาว","น้องชาย"],"correctIndex":1,"type":"vocab"},{"question":"\"Brother\" แปลว่าอะไร?","options":["พี่สาว","น้องสาว","พี่ชาย/น้องชาย","ลูกพี่ลูกน้อง"],"correctIndex":2,"type":"vocab"},{"question":"พ่อเป็นยังไง?","options":["kind","short","tall","funny"],"correctIndex":2,"type":"comprehension"},{"question":"ฉันมีพี่น้องกี่คน?","options":["one","two","three","four"],"correctIndex":1,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-family', 'My Family'),

-- Lesson 2
(1, 2, 'Grandparents and Relatives', 'ปู่ย่าตายายและญาติ',
$$[{"word":"grandfather","phonetic":"แกรนด์ฟาเธอร์","meaning":"ปู่/ตา","partOfSpeech":"n."},{"word":"grandmother","phonetic":"แกรนด์มาเธอร์","meaning":"ย่า/ยาย","partOfSpeech":"n."},{"word":"uncle","phonetic":"อังเคิล","meaning":"ลุง/น้า/อา","partOfSpeech":"n."},{"word":"aunt","phonetic":"อานท์","meaning":"ป้า/น้า/อา","partOfSpeech":"n."},{"word":"cousin","phonetic":"คัสซิน","meaning":"ลูกพี่ลูกน้อง","partOfSpeech":"n."},{"word":"old","phonetic":"โอลด์","meaning":"แก่/เก่า","partOfSpeech":"adj."}]$$::jsonb,
$$[[{"english":"My","thai":"มาย"},{"english":"grandfather","thai":"แกรนด์ฟาเธอร์"},{"english":"is","thai":"อิส"},{"english":"seventy","thai":"เซเวนตี"},{"english":"years","thai":"เยียร์ส"},{"english":"old.","thai":"โอลด์"}],[{"english":"My","thai":"มาย"},{"english":"grandmother","thai":"แกรนด์มาเธอร์"},{"english":"cooks","thai":"คุ๊คส์"},{"english":"very","thai":"เวรี"},{"english":"well.","thai":"เวล"}],[{"english":"I","thai":"ไอ"},{"english":"have","thai":"แฮฟ"},{"english":"three","thai":"ทรี"},{"english":"cousins.","thai":"คัสซินส์"}],[{"english":"We","thai":"วี"},{"english":"visit","thai":"วิซิท"},{"english":"our","thai":"เอาร์"},{"english":"grandparents","thai":"แกรนด์แพเรนทส์"},{"english":"every","thai":"เอฟรี"},{"english":"Sunday.","thai":"ซันเดย์"}]]$$::jsonb,
'ปู่ของฉันอายุเจ็ดสิบปี ย่าของฉันทำอาหารเก่งมาก ฉันมีลูกพี่ลูกน้องสามคน เราไปเยี่ยมปู่ย่าทุกวันอาทิตย์',
'Extended family gathering at grandparents house, cartoon style, warm atmosphere',
$$[{"question":"\"Grandmother\" แปลว่าอะไร?","options":["ปู่/ตา","ย่า/ยาย","ลุง","ป้า"],"correctIndex":1,"type":"vocab"},{"question":"\"Cousin\" แปลว่าอะไร?","options":["พี่ชาย","น้องสาว","ลูกพี่ลูกน้อง","เพื่อน"],"correctIndex":2,"type":"vocab"},{"question":"ปู่อายุเท่าไหร่?","options":["sixty","seventy","eighty","ninety"],"correctIndex":1,"type":"comprehension"},{"question":"เราไปเยี่ยมปู่ย่าวันอะไร?","options":["Saturday","Sunday","Monday","Friday"],"correctIndex":1,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-family', 'Grandparents'),

-- Lesson 3
(1, 3, 'Describing Family Members', 'บรรยายสมาชิกในครอบครัว',
$$[{"word":"tall","phonetic":"ทอล","meaning":"สูง","partOfSpeech":"adj."},{"word":"short","phonetic":"ชอร์ท","meaning":"เตี้ย","partOfSpeech":"adj."},{"word":"young","phonetic":"ยัง","meaning":"อายุน้อย/หนุ่มสาว","partOfSpeech":"adj."},{"word":"kind","phonetic":"ไคนด์","meaning":"ใจดี","partOfSpeech":"adj."},{"word":"funny","phonetic":"ฟันนี","meaning":"ตลก","partOfSpeech":"adj."},{"word":"smart","phonetic":"สมาร์ท","meaning":"ฉลาด","partOfSpeech":"adj."}]$$::jsonb,
$$[[{"english":"My","thai":"มาย"},{"english":"sister","thai":"ซิสเตอร์"},{"english":"is","thai":"อิส"},{"english":"tall","thai":"ทอล"},{"english":"and","thai":"แอนด์"},{"english":"smart.","thai":"สมาร์ท"}],[{"english":"My","thai":"มาย"},{"english":"brother","thai":"บราเธอร์"},{"english":"is","thai":"อิส"},{"english":"short","thai":"ชอร์ท"},{"english":"and","thai":"แอนด์"},{"english":"funny.","thai":"ฟันนี"}],[{"english":"My","thai":"มาย"},{"english":"mother","thai":"มาเธอร์"},{"english":"is","thai":"อิส"},{"english":"kind","thai":"ไคนด์"},{"english":"and","thai":"แอนด์"},{"english":"young.","thai":"ยัง"}],[{"english":"What","thai":"ว็อท"},{"english":"is","thai":"อิส"},{"english":"your","thai":"ยัวร์"},{"english":"family","thai":"แฟมิลี"},{"english":"like?","thai":"ไลค์?"}]]$$::jsonb,
'พี่สาวของฉันสูงและฉลาด น้องชายของฉันเตี้ยและตลก แม่ของฉันใจดีและยังสาว ครอบครัวของคุณเป็นยังไง?',
'Cartoon family members with different heights and personalities, fun and colorful',
$$[{"question":"\"Tall\" แปลว่าอะไร?","options":["เตี้ย","สูง","อ้วน","ผอม"],"correctIndex":1,"type":"vocab"},{"question":"\"Kind\" แปลว่าอะไร?","options":["ตลก","ฉลาด","ใจดี","สวย"],"correctIndex":2,"type":"vocab"},{"question":"พี่สาวเป็นยังไง?","options":["short and funny","tall and smart","kind and young","old and tall"],"correctIndex":1,"type":"comprehension"},{"question":"น้องชายเป็นยังไง?","options":["tall and smart","kind and young","short and funny","old and kind"],"correctIndex":2,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-family', 'Describing Family'),

-- Lesson 4
(1, 4, 'Family Activities', 'กิจกรรมในครอบครัว',
$$[{"word":"cook","phonetic":"คุ๊ค","meaning":"ทำอาหาร","partOfSpeech":"v."},{"word":"watch TV","phonetic":"ว็อทช์ ทีวี","meaning":"ดูทีวี","partOfSpeech":"phr."},{"word":"play","phonetic":"เพลย์","meaning":"เล่น","partOfSpeech":"v."},{"word":"together","phonetic":"ทูเกเธอร์","meaning":"ด้วยกัน","partOfSpeech":"adv."},{"word":"weekend","phonetic":"วีคเอนด์","meaning":"วันหยุดสุดสัปดาห์","partOfSpeech":"n."},{"word":"dinner","phonetic":"ดินเนอร์","meaning":"อาหารเย็น","partOfSpeech":"n."}]$$::jsonb,
$$[[{"english":"On","thai":"ออน"},{"english":"weekends,","thai":"วีคเอนดส์,"},{"english":"my","thai":"มาย"},{"english":"family","thai":"แฟมิลี"},{"english":"cooks","thai":"คุ๊คส์"},{"english":"together.","thai":"ทูเกเธอร์"}],[{"english":"We","thai":"วี"},{"english":"watch","thai":"ว็อทช์"},{"english":"TV","thai":"ทีวี"},{"english":"after","thai":"อาฟเตอร์"},{"english":"dinner.","thai":"ดินเนอร์"}],[{"english":"My","thai":"มาย"},{"english":"brother","thai":"บราเธอร์"},{"english":"and","thai":"แอนด์"},{"english":"I","thai":"ไอ"},{"english":"play","thai":"เพลย์"},{"english":"games.","thai":"เกมส์"}],[{"english":"I","thai":"ไอ"},{"english":"love","thai":"ลัฟ"},{"english":"spending","thai":"สเพนดิง"},{"english":"time","thai":"ไทม์"},{"english":"with","thai":"วิธ"},{"english":"my","thai":"มาย"},{"english":"family.","thai":"แฟมิลี"}]]$$::jsonb,
'วันหยุดสุดสัปดาห์ครอบครัวของฉันทำอาหารด้วยกัน เราดูทีวีหลังอาหารเย็น ฉันและน้องชายเล่นเกม ฉันชอบใช้เวลากับครอบครัว',
'Happy family cooking together in kitchen, watching TV, playing games, cartoon style',
$$[{"question":"\"Cook\" แปลว่าอะไร?","options":["กิน","ดื่ม","ทำอาหาร","ซื้อ"],"correctIndex":2,"type":"vocab"},{"question":"\"Together\" แปลว่าอะไร?","options":["คนเดียว","ด้วยกัน","แยกกัน","บางครั้ง"],"correctIndex":1,"type":"vocab"},{"question":"ครอบครัวทำอะไรวันหยุด?","options":["go shopping","cook together","go to school","work"],"correctIndex":1,"type":"comprehension"},{"question":"ฉันและน้องชายทำอะไร?","options":["cook","watch TV","play games","sleep"],"correctIndex":2,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-family', 'Family Activities'),

-- Lesson 5
(1, 5, 'My Pet', 'สัตว์เลี้ยงของฉัน',
$$[{"word":"pet","phonetic":"เพ็ท","meaning":"สัตว์เลี้ยง","partOfSpeech":"n."},{"word":"dog","phonetic":"ด็อก","meaning":"หมา","partOfSpeech":"n."},{"word":"cat","phonetic":"แคท","meaning":"แมว","partOfSpeech":"n."},{"word":"feed","phonetic":"ฟีด","meaning":"ให้อาหาร","partOfSpeech":"v."},{"word":"walk","phonetic":"วอล์ค","meaning":"เดิน/พาเดิน","partOfSpeech":"v."},{"word":"cute","phonetic":"คิวท์","meaning":"น่ารัก","partOfSpeech":"adj."}]$$::jsonb,
$$[[{"english":"I","thai":"ไอ"},{"english":"have","thai":"แฮฟ"},{"english":"a","thai":"อะ"},{"english":"pet","thai":"เพ็ท"},{"english":"dog.","thai":"ด็อก"}],[{"english":"His","thai":"ฮิส"},{"english":"name","thai":"เนม"},{"english":"is","thai":"อิส"},{"english":"Max.","thai":"แม็กซ์"}],[{"english":"He","thai":"ฮี"},{"english":"is","thai":"อิส"},{"english":"very","thai":"เวรี"},{"english":"cute.","thai":"คิวท์"}],[{"english":"I","thai":"ไอ"},{"english":"feed","thai":"ฟีด"},{"english":"him","thai":"ฮิม"},{"english":"every","thai":"เอฟรี"},{"english":"day.","thai":"เดย์"}],[{"english":"We","thai":"วี"},{"english":"walk","thai":"วอล์ค"},{"english":"in","thai":"อิน"},{"english":"the","thai":"เดอะ"},{"english":"park","thai":"พาร์ค"},{"english":"together.","thai":"ทูเกเธอร์"}]]$$::jsonb,
'ฉันมีหมาเลี้ยง ชื่อแม็กซ์ เขาน่ารักมาก ฉันให้อาหารเขาทุกวัน เราเดินเล่นในสวนด้วยกัน',
'Child playing with cute dog in park, cartoon style, sunny day',
$$[{"question":"\"Pet\" แปลว่าอะไร?","options":["สัตว์ป่า","สัตว์เลี้ยง","สัตว์ทะเล","สัตว์ฟาร์ม"],"correctIndex":1,"type":"vocab"},{"question":"\"Feed\" แปลว่าอะไร?","options":["อาบน้ำ","ให้อาหาร","พาเดิน","เล่นด้วย"],"correctIndex":1,"type":"vocab"},{"question":"หมาชื่ออะไร?","options":["Buddy","Rex","Max","Lucky"],"correctIndex":2,"type":"comprehension"},{"question":"ฉันและหมาไปที่ไหนด้วยกัน?","options":["school","park","market","home"],"correctIndex":1,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-family', 'My Pet'),

-- ==========================================
-- Module: core-a1-daily (6 lessons)
-- ==========================================

-- Lesson 1
(1, 1, 'My Morning Routine', 'กิจวัตรตอนเช้า',
$$[{"word":"wake up","phonetic":"เวค อัพ","meaning":"ตื่นนอน","partOfSpeech":"phr."},{"word":"brush teeth","phonetic":"บรัช ทีธ","meaning":"แปรงฟัน","partOfSpeech":"phr."},{"word":"shower","phonetic":"ชาวเวอร์","meaning":"อาบน้ำ","partOfSpeech":"n./v."},{"word":"breakfast","phonetic":"เบรคฟาสท์","meaning":"อาหารเช้า","partOfSpeech":"n."},{"word":"get dressed","phonetic":"เก็ท เดรสท์","meaning":"แต่งตัว","partOfSpeech":"phr."},{"word":"go to school","phonetic":"โก ทู สคูล","meaning":"ไปโรงเรียน","partOfSpeech":"phr."}]$$::jsonb,
$$[[{"english":"I","thai":"ไอ"},{"english":"wake","thai":"เวค"},{"english":"up","thai":"อัพ"},{"english":"at","thai":"แอท"},{"english":"six","thai":"ซิกซ์"},{"english":"o''clock.","thai":"โอคล็อค"}],[{"english":"I","thai":"ไอ"},{"english":"brush","thai":"บรัช"},{"english":"my","thai":"มาย"},{"english":"teeth","thai":"ทีธ"},{"english":"and","thai":"แอนด์"},{"english":"take","thai":"เทค"},{"english":"a","thai":"อะ"},{"english":"shower.","thai":"ชาวเวอร์"}],[{"english":"Then","thai":"เดน"},{"english":"I","thai":"ไอ"},{"english":"eat","thai":"อีท"},{"english":"breakfast.","thai":"เบรคฟาสท์"}],[{"english":"I","thai":"ไอ"},{"english":"get","thai":"เก็ท"},{"english":"dressed","thai":"เดรสท์"},{"english":"and","thai":"แอนด์"},{"english":"go","thai":"โก"},{"english":"to","thai":"ทู"},{"english":"school.","thai":"สคูล"}]]$$::jsonb,
'ฉันตื่นนอนตอนหกโมง ฉันแปรงฟันและอาบน้ำ จากนั้นฉันกินอาหารเช้า ฉันแต่งตัวและไปโรงเรียน',
'Cartoon child doing morning routine - waking up, brushing teeth, eating breakfast, going to school',
$$[{"question":"\"Wake up\" แปลว่าอะไร?","options":["นอนหลับ","ตื่นนอน","อาบน้ำ","แต่งตัว"],"correctIndex":1,"type":"vocab"},{"question":"\"Breakfast\" แปลว่าอะไร?","options":["อาหารเช้า","อาหารกลางวัน","อาหารเย็น","ของว่าง"],"correctIndex":0,"type":"vocab"},{"question":"ฉันตื่นนอนกี่โมง?","options":["5:00","6:00","7:00","8:00"],"correctIndex":1,"type":"comprehension"},{"question":"ฉันทำอะไรก่อนไปโรงเรียน?","options":["play games","watch TV","eat breakfast","sleep more"],"correctIndex":2,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-daily', 'Morning Routine'),

-- Lesson 2
(1, 2, 'At School', 'ที่โรงเรียน',
$$[{"word":"school","phonetic":"สคูล","meaning":"โรงเรียน","partOfSpeech":"n."},{"word":"classroom","phonetic":"คลาสรูม","meaning":"ห้องเรียน","partOfSpeech":"n."},{"word":"study","phonetic":"สตัดดี","meaning":"เรียน/ศึกษา","partOfSpeech":"v."},{"word":"homework","phonetic":"โฮมเวิร์ค","meaning":"การบ้าน","partOfSpeech":"n."},{"word":"friend","phonetic":"เฟรนด์","meaning":"เพื่อน","partOfSpeech":"n."},{"word":"recess","phonetic":"รีเซส","meaning":"พักกลางวัน","partOfSpeech":"n."}]$$::jsonb,
$$[[{"english":"I","thai":"ไอ"},{"english":"go","thai":"โก"},{"english":"to","thai":"ทู"},{"english":"school","thai":"สคูล"},{"english":"every","thai":"เอฟรี"},{"english":"day.","thai":"เดย์"}],[{"english":"I","thai":"ไอ"},{"english":"study","thai":"สตัดดี"},{"english":"in","thai":"อิน"},{"english":"the","thai":"เดอะ"},{"english":"classroom.","thai":"คลาสรูม"}],[{"english":"I","thai":"ไอ"},{"english":"play","thai":"เพลย์"},{"english":"with","thai":"วิธ"},{"english":"my","thai":"มาย"},{"english":"friends","thai":"เฟรนดส์"},{"english":"at","thai":"แอท"},{"english":"recess.","thai":"รีเซส"}],[{"english":"I","thai":"ไอ"},{"english":"do","thai":"ดู"},{"english":"my","thai":"มาย"},{"english":"homework","thai":"โฮมเวิร์ค"},{"english":"after","thai":"อาฟเตอร์"},{"english":"school.","thai":"สคูล"}]]$$::jsonb,
'ฉันไปโรงเรียนทุกวัน ฉันเรียนในห้องเรียน ฉันเล่นกับเพื่อนตอนพักกลางวัน ฉันทำการบ้านหลังเลิกเรียน',
'Cartoon school scene with students in classroom and playing at recess, bright and colorful',
$$[{"question":"\"Classroom\" แปลว่าอะไร?","options":["โรงเรียน","ห้องเรียน","ห้องสมุด","สนามเด็กเล่น"],"correctIndex":1,"type":"vocab"},{"question":"\"Homework\" แปลว่าอะไร?","options":["การสอบ","การบ้าน","โปรเจกต์","รายงาน"],"correctIndex":1,"type":"vocab"},{"question":"ฉันเล่นกับเพื่อนเมื่อไหร่?","options":["before school","during class","at recess","after homework"],"correctIndex":2,"type":"comprehension"},{"question":"ฉันทำการบ้านเมื่อไหร่?","options":["before school","at recess","during lunch","after school"],"correctIndex":3,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-daily', 'At School'),

-- Lesson 3
(1, 3, 'After School Activities', 'กิจกรรมหลังเลิกเรียน',
$$[{"word":"after school","phonetic":"อาฟเตอร์ สคูล","meaning":"หลังเลิกเรียน","partOfSpeech":"phr."},{"word":"sport","phonetic":"สปอร์ท","meaning":"กีฬา","partOfSpeech":"n."},{"word":"music","phonetic":"มิวสิค","meaning":"ดนตรี","partOfSpeech":"n."},{"word":"read","phonetic":"รีด","meaning":"อ่าน","partOfSpeech":"v."},{"word":"hobby","phonetic":"ฮ็อบบี","meaning":"งานอดิเรก","partOfSpeech":"n."},{"word":"tired","phonetic":"ไทเออร์ด","meaning":"เหนื่อย","partOfSpeech":"adj."}]$$::jsonb,
$$[[{"english":"After","thai":"อาฟเตอร์"},{"english":"school,","thai":"สคูล,"},{"english":"I","thai":"ไอ"},{"english":"play","thai":"เพลย์"},{"english":"sport.","thai":"สปอร์ท"}],[{"english":"On","thai":"ออน"},{"english":"Tuesday,","thai":"ทิวส์เดย์,"},{"english":"I","thai":"ไอ"},{"english":"have","thai":"แฮฟ"},{"english":"music","thai":"มิวสิค"},{"english":"class.","thai":"คลาส"}],[{"english":"I","thai":"ไอ"},{"english":"like","thai":"ไลค์"},{"english":"to","thai":"ทู"},{"english":"read","thai":"รีด"},{"english":"books","thai":"บุ๊คส์"},{"english":"too.","thai":"ทู"}],[{"english":"My","thai":"มาย"},{"english":"hobby","thai":"ฮ็อบบี"},{"english":"is","thai":"อิส"},{"english":"drawing.","thai":"ดรอวิง"}],[{"english":"I","thai":"ไอ"},{"english":"am","thai":"แอม"},{"english":"tired","thai":"ไทเออร์ด"},{"english":"but","thai":"บัท"},{"english":"happy!","thai":"แฮปปี!"}]]$$::jsonb,
'หลังเลิกเรียนฉันเล่นกีฬา วันอังคารฉันมีคลาสดนตรี ฉันชอบอ่านหนังสือด้วย งานอดิเรกของฉันคือวาดรูป ฉันเหนื่อยแต่มีความสุข!',
'Cartoon child doing various after-school activities - sports, music, reading, drawing',
$$[{"question":"\"Hobby\" แปลว่าอะไร?","options":["งาน","การบ้าน","งานอดิเรก","กีฬา"],"correctIndex":2,"type":"vocab"},{"question":"\"Tired\" แปลว่าอะไร?","options":["หิว","ง่วง","เหนื่อย","เบื่อ"],"correctIndex":2,"type":"vocab"},{"question":"งานอดิเรกของฉันคืออะไร?","options":["reading","music","sport","drawing"],"correctIndex":3,"type":"comprehension"},{"question":"ฉันมีคลาสดนตรีวันอะไร?","options":["Monday","Tuesday","Wednesday","Thursday"],"correctIndex":1,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-daily', 'After School'),

-- Lesson 4
(1, 4, 'Evening and Bedtime', 'ตอนเย็นและก่อนนอน',
$$[{"word":"evening","phonetic":"อีฟนิง","meaning":"ตอนเย็น","partOfSpeech":"n."},{"word":"dinner","phonetic":"ดินเนอร์","meaning":"อาหารเย็น","partOfSpeech":"n."},{"word":"bath","phonetic":"บาธ","meaning":"อาบน้ำ","partOfSpeech":"n."},{"word":"sleep","phonetic":"สลีป","meaning":"นอนหลับ","partOfSpeech":"v."},{"word":"dream","phonetic":"ดรีม","meaning":"ฝัน","partOfSpeech":"n./v."},{"word":"bed","phonetic":"เบด","meaning":"เตียง","partOfSpeech":"n."}]$$::jsonb,
$$[[{"english":"In","thai":"อิน"},{"english":"the","thai":"เดอะ"},{"english":"evening,","thai":"อีฟนิง,"},{"english":"we","thai":"วี"},{"english":"eat","thai":"อีท"},{"english":"dinner.","thai":"ดินเนอร์"}],[{"english":"After","thai":"อาฟเตอร์"},{"english":"dinner,","thai":"ดินเนอร์,"},{"english":"I","thai":"ไอ"},{"english":"take","thai":"เทค"},{"english":"a","thai":"อะ"},{"english":"bath.","thai":"บาธ"}],[{"english":"I","thai":"ไอ"},{"english":"read","thai":"รีด"},{"english":"a","thai":"อะ"},{"english":"book","thai":"บุ๊ค"},{"english":"in","thai":"อิน"},{"english":"bed.","thai":"เบด"}],[{"english":"Then","thai":"เดน"},{"english":"I","thai":"ไอ"},{"english":"sleep","thai":"สลีป"},{"english":"and","thai":"แอนด์"},{"english":"dream.","thai":"ดรีม"}]]$$::jsonb,
'ตอนเย็นเรากินอาหารเย็น หลังอาหารเย็นฉันอาบน้ำ ฉันอ่านหนังสือบนเตียง จากนั้นฉันนอนหลับและฝัน',
'Cozy evening scene - family dinner, child bathing, reading in bed, sleeping, cartoon style',
$$[{"question":"\"Dinner\" แปลว่าอะไร?","options":["อาหารเช้า","อาหารกลางวัน","อาหารเย็น","ของว่าง"],"correctIndex":2,"type":"vocab"},{"question":"\"Sleep\" แปลว่าอะไร?","options":["ตื่น","นอนหลับ","พักผ่อน","นั่ง"],"correctIndex":1,"type":"vocab"},{"question":"ฉันทำอะไรหลังอาหารเย็น?","options":["watch TV","take a bath","do homework","play games"],"correctIndex":1,"type":"comprehension"},{"question":"ฉันทำอะไรบนเตียง?","options":["eat","play","read a book","watch TV"],"correctIndex":2,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-daily', 'Evening Routine'),

-- Lesson 5
(1, 5, 'I Like and I Don''t Like', 'ฉันชอบและไม่ชอบ',
$$[{"word":"like","phonetic":"ไลค์","meaning":"ชอบ","partOfSpeech":"v."},{"word":"don''t like","phonetic":"โดนท์ ไลค์","meaning":"ไม่ชอบ","partOfSpeech":"phr."},{"word":"love","phonetic":"ลัฟ","meaning":"รัก/ชอบมาก","partOfSpeech":"v."},{"word":"hate","phonetic":"เฮท","meaning":"เกลียด","partOfSpeech":"v."},{"word":"favorite","phonetic":"เฟเวอริท","meaning":"ชื่นชอบที่สุด","partOfSpeech":"adj."},{"word":"why","phonetic":"วาย","meaning":"ทำไม","partOfSpeech":"adv."}]$$::jsonb,
$$[[{"english":"I","thai":"ไอ"},{"english":"love","thai":"ลัฟ"},{"english":"playing","thai":"เพลยิง"},{"english":"football.","thai":"ฟุตบอล"}],[{"english":"I","thai":"ไอ"},{"english":"like","thai":"ไลค์"},{"english":"eating","thai":"อีทิง"},{"english":"pizza.","thai":"พิซซ่า"}],[{"english":"I","thai":"ไอ"},{"english":"don''t","thai":"โดนท์"},{"english":"like","thai":"ไลค์"},{"english":"waking","thai":"เวคิง"},{"english":"up","thai":"อัพ"},{"english":"early.","thai":"เอิร์ลี"}],[{"english":"\"Why","thai":"\"วาย"},{"english":"don''t","thai":"โดนท์"},{"english":"you","thai":"ยู"},{"english":"like","thai":"ไลค์"},{"english":"it?\"","thai":"อิท?\""}],[{"english":"\"Because","thai":"\"บีคอส"},{"english":"I","thai":"ไอ"},{"english":"am","thai":"แอม"},{"english":"sleepy!\"","thai":"สลีปี!\""}]]$$::jsonb,
'ฉันชอบเล่นฟุตบอลมาก ฉันชอบกินพิซซ่า ฉันไม่ชอบตื่นเช้า "ทำไมไม่ชอบ?" "เพราะฉันง่วง!"',
'Cartoon child showing likes and dislikes with thumbs up and down, fun expressions',
$$[{"question":"\"Like\" แปลว่าอะไร?","options":["เกลียด","ชอบ","รัก","ไม่แน่ใจ"],"correctIndex":1,"type":"vocab"},{"question":"\"Why\" แปลว่าอะไร?","options":["อะไร","ที่ไหน","เมื่อไหร่","ทำไม"],"correctIndex":3,"type":"vocab"},{"question":"ฉันชอบกีฬาอะไร?","options":["basketball","tennis","football","swimming"],"correctIndex":2,"type":"comprehension"},{"question":"ทำไมฉันไม่ชอบตื่นเช้า?","options":["it is cold","I am hungry","I am sleepy","it is boring"],"correctIndex":2,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-daily', 'Likes and Dislikes'),

-- Lesson 6
(1, 6, 'My Week', 'สัปดาห์ของฉัน',
$$[{"word":"busy","phonetic":"บิซซี","meaning":"ยุ่ง","partOfSpeech":"adj."},{"word":"free","phonetic":"ฟรี","meaning":"ว่าง","partOfSpeech":"adj."},{"word":"usually","phonetic":"ยูชวลลี","meaning":"ปกติแล้ว","partOfSpeech":"adv."},{"word":"sometimes","phonetic":"ซัมไทมส์","meaning":"บางครั้ง","partOfSpeech":"adv."},{"word":"always","phonetic":"ออลเวย์ส","meaning":"เสมอ","partOfSpeech":"adv."},{"word":"never","phonetic":"เนเวอร์","meaning":"ไม่เคย","partOfSpeech":"adv."}]$$::jsonb,
$$[[{"english":"I","thai":"ไอ"},{"english":"am","thai":"แอม"},{"english":"always","thai":"ออลเวย์ส"},{"english":"busy","thai":"บิซซี"},{"english":"on","thai":"ออน"},{"english":"weekdays.","thai":"วีคเดย์ส"}],[{"english":"I","thai":"ไอ"},{"english":"usually","thai":"ยูชวลลี"},{"english":"study","thai":"สตัดดี"},{"english":"in","thai":"อิน"},{"english":"the","thai":"เดอะ"},{"english":"evening.","thai":"อีฟนิง"}],[{"english":"I","thai":"ไอ"},{"english":"sometimes","thai":"ซัมไทมส์"},{"english":"go","thai":"โก"},{"english":"to","thai":"ทู"},{"english":"the","thai":"เดอะ"},{"english":"park.","thai":"พาร์ค"}],[{"english":"I","thai":"ไอ"},{"english":"never","thai":"เนเวอร์"},{"english":"miss","thai":"มิส"},{"english":"school.","thai":"สคูล"}]]$$::jsonb,
'ฉันยุ่งเสมอในวันธรรมดา ปกติฉันเรียนตอนเย็น บางครั้งฉันไปสวนสาธารณะ ฉันไม่เคยขาดเรียน',
'Weekly planner with cartoon activities, colorful schedule board',
$$[{"question":"\"Always\" แปลว่าอะไร?","options":["บางครั้ง","ปกติ","เสมอ","ไม่เคย"],"correctIndex":2,"type":"vocab"},{"question":"\"Never\" แปลว่าอะไร?","options":["เสมอ","บางครั้ง","ปกติ","ไม่เคย"],"correctIndex":3,"type":"vocab"},{"question":"ฉันยุ่งเมื่อไหร่?","options":["on weekends","on weekdays","on holidays","on Sundays"],"correctIndex":1,"type":"comprehension"},{"question":"ฉันไม่เคยทำอะไร?","options":["go to park","study","miss school","eat dinner"],"correctIndex":2,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-daily', 'My Week'),

-- ==========================================
-- Module: core-a1-food (5 lessons)
-- ==========================================

-- Lesson 1
(1, 1, 'I Am Hungry!', 'ฉันหิว!',
$$[{"word":"hungry","phonetic":"ฮังกรี","meaning":"หิว","partOfSpeech":"adj."},{"word":"thirsty","phonetic":"เธิร์สตี","meaning":"กระหายน้ำ","partOfSpeech":"adj."},{"word":"food","phonetic":"ฟูด","meaning":"อาหาร","partOfSpeech":"n."},{"word":"meal","phonetic":"มีล","meaning":"มื้ออาหาร","partOfSpeech":"n."},{"word":"delicious","phonetic":"ดิลิเชียส","meaning":"อร่อย","partOfSpeech":"adj."},{"word":"full","phonetic":"ฟูล","meaning":"อิ่ม","partOfSpeech":"adj."}]$$::jsonb,
$$[[{"english":"I","thai":"ไอ"},{"english":"am","thai":"แอม"},{"english":"very","thai":"เวรี"},{"english":"hungry.","thai":"ฮังกรี"}],[{"english":"I","thai":"ไอ"},{"english":"want","thai":"วอนท์"},{"english":"to","thai":"ทู"},{"english":"eat","thai":"อีท"},{"english":"a","thai":"อะ"},{"english":"meal.","thai":"มีล"}],[{"english":"The","thai":"เดอะ"},{"english":"food","thai":"ฟูด"},{"english":"is","thai":"อิส"},{"english":"delicious!","thai":"ดิลิเชียส!"}],[{"english":"Now","thai":"นาว"},{"english":"I","thai":"ไอ"},{"english":"am","thai":"แอม"},{"english":"full","thai":"ฟูล"},{"english":"and","thai":"แอนด์"},{"english":"happy.","thai":"แฮปปี"}]]$$::jsonb,
'ฉันหิวมาก ฉันอยากกินอาหาร อาหารอร่อยมาก! ตอนนี้ฉันอิ่มและมีความสุข',
'Cartoon child looking hungry, then eating delicious food, happy expression',
$$[{"question":"\"Hungry\" แปลว่าอะไร?","options":["อิ่ม","หิว","กระหาย","เหนื่อย"],"correctIndex":1,"type":"vocab"},{"question":"\"Delicious\" แปลว่าอะไร?","options":["แพง","ถูก","อร่อย","เผ็ด"],"correctIndex":2,"type":"vocab"},{"question":"ฉันรู้สึกยังไงตอนแรก?","options":["full","happy","hungry","tired"],"correctIndex":2,"type":"comprehension"},{"question":"ฉันรู้สึกยังไงหลังกินอาหาร?","options":["hungry and sad","full and happy","tired and sleepy","thirsty and hungry"],"correctIndex":1,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-food', 'Hunger and Food'),

-- Lesson 2
(1, 2, 'Fruits and Vegetables', 'ผลไม้และผัก',
$$[{"word":"apple","phonetic":"แอปเปิล","meaning":"แอปเปิล","partOfSpeech":"n."},{"word":"banana","phonetic":"บะนานา","meaning":"กล้วย","partOfSpeech":"n."},{"word":"mango","phonetic":"แมงโก","meaning":"มะม่วง","partOfSpeech":"n."},{"word":"vegetable","phonetic":"เวจิทะเบิล","meaning":"ผัก","partOfSpeech":"n."},{"word":"carrot","phonetic":"แคร็อท","meaning":"แครอท","partOfSpeech":"n."},{"word":"healthy","phonetic":"เฮลธี","meaning":"มีประโยชน์/สุขภาพดี","partOfSpeech":"adj."}]$$::jsonb,
$$[[{"english":"Fruits","thai":"ฟรูทส์"},{"english":"and","thai":"แอนด์"},{"english":"vegetables","thai":"เวจิทะเบิลส์"},{"english":"are","thai":"อาร์"},{"english":"healthy.","thai":"เฮลธี"}],[{"english":"I","thai":"ไอ"},{"english":"eat","thai":"อีท"},{"english":"an","thai":"แอน"},{"english":"apple","thai":"แอปเปิล"},{"english":"every","thai":"เอฟรี"},{"english":"day.","thai":"เดย์"}],[{"english":"My","thai":"มาย"},{"english":"favorite","thai":"เฟเวอริท"},{"english":"fruit","thai":"ฟรูท"},{"english":"is","thai":"อิส"},{"english":"mango.","thai":"แมงโก"}],[{"english":"I","thai":"ไอ"},{"english":"don''t","thai":"โดนท์"},{"english":"like","thai":"ไลค์"},{"english":"carrots","thai":"แคร็อทส์"},{"english":"but","thai":"บัท"},{"english":"they","thai":"เดย์"},{"english":"are","thai":"อาร์"},{"english":"good","thai":"กู๊ด"},{"english":"for","thai":"ฟอร์"},{"english":"me.","thai":"มี"}]]$$::jsonb,
'ผลไม้และผักมีประโยชน์ ฉันกินแอปเปิลทุกวัน ผลไม้ที่ฉันชอบที่สุดคือมะม่วง ฉันไม่ชอบแครอทแต่มันดีต่อสุขภาพ',
'Colorful fruits and vegetables display, cartoon style, market or kitchen setting',
$$[{"question":"\"Healthy\" แปลว่าอะไร?","options":["อร่อย","แพง","มีประโยชน์","หวาน"],"correctIndex":2,"type":"vocab"},{"question":"\"Vegetable\" แปลว่าอะไร?","options":["ผลไม้","ผัก","เนื้อ","ขนม"],"correctIndex":1,"type":"vocab"},{"question":"ผลไม้ที่ฉันชอบที่สุดคืออะไร?","options":["apple","banana","mango","orange"],"correctIndex":2,"type":"comprehension"},{"question":"ทำไมฉันกินแครอทแม้ไม่ชอบ?","options":["it is cheap","it is delicious","it is good for me","it is my favorite"],"correctIndex":2,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-food', 'Fruits and Vegetables'),

-- Lesson 3
(1, 3, 'At the Restaurant', 'ที่ร้านอาหาร',
$$[{"word":"restaurant","phonetic":"เรสเทอรองท์","meaning":"ร้านอาหาร","partOfSpeech":"n."},{"word":"menu","phonetic":"เมนู","meaning":"เมนู","partOfSpeech":"n."},{"word":"order","phonetic":"ออร์เดอร์","meaning":"สั่ง","partOfSpeech":"v."},{"word":"waiter","phonetic":"เวเทอร์","meaning":"พนักงานเสิร์ฟ","partOfSpeech":"n."},{"word":"bill","phonetic":"บิล","meaning":"บิล/ใบเสร็จ","partOfSpeech":"n."},{"word":"please","phonetic":"พลีส","meaning":"กรุณา","partOfSpeech":"adv."}]$$::jsonb,
$$[[{"english":"We","thai":"วี"},{"english":"go","thai":"โก"},{"english":"to","thai":"ทู"},{"english":"a","thai":"อะ"},{"english":"restaurant.","thai":"เรสเทอรองท์"}],[{"english":"\"Can","thai":"\"แคน"},{"english":"I","thai":"ไอ"},{"english":"see","thai":"ซี"},{"english":"the","thai":"เดอะ"},{"english":"menu,","thai":"เมนู,"},{"english":"please?\"","thai":"พลีส?\""}],[{"english":"\"I","thai":"\"ไอ"},{"english":"would","thai":"วูด"},{"english":"like","thai":"ไลค์"},{"english":"fried","thai":"ไฟรด์"},{"english":"rice,","thai":"ไรซ์,"},{"english":"please.\"","thai":"พลีส\""}],[{"english":"\"Can","thai":"\"แคน"},{"english":"I","thai":"ไอ"},{"english":"have","thai":"แฮฟ"},{"english":"the","thai":"เดอะ"},{"english":"bill,","thai":"บิล,"},{"english":"please?\"","thai":"พลีส?\""}]]$$::jsonb,
'เราไปร้านอาหาร "ขอดูเมนูได้ไหมครับ?" "ขอข้าวผัดครับ" "ขอบิลด้วยครับ"',
'Cartoon family at restaurant, waiter taking order, menu visible, cozy setting',
$$[{"question":"\"Order\" แปลว่าอะไร?","options":["จ่าย","สั่ง","รับ","คืน"],"correctIndex":1,"type":"vocab"},{"question":"\"Bill\" แปลว่าอะไร?","options":["เมนู","อาหาร","บิล/ใบเสร็จ","โต๊ะ"],"correctIndex":2,"type":"vocab"},{"question":"ฉันสั่งอาหารอะไร?","options":["noodles","fried rice","soup","salad"],"correctIndex":1,"type":"comprehension"},{"question":"ฉันขออะไรตอนท้าย?","options":["menu","more food","the bill","water"],"correctIndex":2,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-food', 'At the Restaurant'),

-- Lesson 4
(1, 4, 'I Can Cook!', 'ฉันทำอาหารได้!',
$$[{"word":"cook","phonetic":"คุ๊ค","meaning":"ทำอาหาร","partOfSpeech":"v."},{"word":"recipe","phonetic":"เรซิพี","meaning":"สูตรอาหาร","partOfSpeech":"n."},{"word":"ingredient","phonetic":"อินกรีเดียนท์","meaning":"ส่วนผสม","partOfSpeech":"n."},{"word":"mix","phonetic":"มิกซ์","meaning":"ผสม","partOfSpeech":"v."},{"word":"boil","phonetic":"บอยล์","meaning":"ต้ม","partOfSpeech":"v."},{"word":"fry","phonetic":"ไฟร์","meaning":"ทอด/ผัด","partOfSpeech":"v."}]$$::jsonb,
$$[[{"english":"Today","thai":"ทูเดย์"},{"english":"I","thai":"ไอ"},{"english":"cook","thai":"คุ๊ค"},{"english":"with","thai":"วิธ"},{"english":"my","thai":"มาย"},{"english":"mom.","thai":"มัม"}],[{"english":"We","thai":"วี"},{"english":"follow","thai":"ฟอลโลว์"},{"english":"a","thai":"อะ"},{"english":"recipe.","thai":"เรซิพี"}],[{"english":"First,","thai":"เฟิร์สท์,"},{"english":"we","thai":"วี"},{"english":"mix","thai":"มิกซ์"},{"english":"the","thai":"เดอะ"},{"english":"ingredients.","thai":"อินกรีเดียนทส์"}],[{"english":"Then","thai":"เดน"},{"english":"we","thai":"วี"},{"english":"fry","thai":"ไฟร์"},{"english":"the","thai":"เดอะ"},{"english":"egg.","thai":"เอ็ก"}],[{"english":"It","thai":"อิท"},{"english":"smells","thai":"สเมลส์"},{"english":"delicious!","thai":"ดิลิเชียส!"}]]$$::jsonb,
'วันนี้ฉันทำอาหารกับแม่ เราทำตามสูตรอาหาร ก่อนอื่นเราผสมส่วนผสม จากนั้นเราทอดไข่ มันหอมอร่อยมาก!',
'Child cooking with parent in kitchen, following recipe, cartoon style, warm kitchen',
$$[{"question":"\"Recipe\" แปลว่าอะไร?","options":["ส่วนผสม","สูตรอาหาร","เครื่องครัว","อาหาร"],"correctIndex":1,"type":"vocab"},{"question":"\"Fry\" แปลว่าอะไร?","options":["ต้ม","อบ","ทอด/ผัด","นึ่ง"],"correctIndex":2,"type":"vocab"},{"question":"ฉันทำอาหารกับใคร?","options":["dad","sister","mom","friend"],"correctIndex":2,"type":"comprehension"},{"question":"เราทำอะไรก่อน?","options":["fry the egg","boil water","mix ingredients","eat"],"correctIndex":2,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-food', 'Cooking'),

-- Lesson 5
(1, 5, 'My Favorite Food', 'อาหารที่ฉันชอบ',
$$[{"word":"favorite","phonetic":"เฟเวอริท","meaning":"ชื่นชอบที่สุด","partOfSpeech":"adj."},{"word":"spicy","phonetic":"สไปซี","meaning":"เผ็ด","partOfSpeech":"adj."},{"word":"sweet","phonetic":"สวีท","meaning":"หวาน","partOfSpeech":"adj."},{"word":"sour","phonetic":"เซาร์","meaning":"เปรี้ยว","partOfSpeech":"adj."},{"word":"salty","phonetic":"ซอลตี","meaning":"เค็ม","partOfSpeech":"adj."},{"word":"taste","phonetic":"เทสท์","meaning":"รสชาติ","partOfSpeech":"n."}]$$::jsonb,
$$[[{"english":"My","thai":"มาย"},{"english":"favorite","thai":"เฟเวอริท"},{"english":"food","thai":"ฟูด"},{"english":"is","thai":"อิส"},{"english":"pad","thai":"แพด"},{"english":"thai.","thai":"ไทย"}],[{"english":"It","thai":"อิท"},{"english":"is","thai":"อิส"},{"english":"a","thai":"อะ"},{"english":"little","thai":"ลิทเทิล"},{"english":"spicy","thai":"สไปซี"},{"english":"and","thai":"แอนด์"},{"english":"sour.","thai":"เซาร์"}],[{"english":"I","thai":"ไอ"},{"english":"also","thai":"ออลโซ"},{"english":"love","thai":"ลัฟ"},{"english":"mango","thai":"แมงโก"},{"english":"sticky","thai":"สติ๊กกี"},{"english":"rice.","thai":"ไรซ์"}],[{"english":"It","thai":"อิท"},{"english":"is","thai":"อิส"},{"english":"sweet","thai":"สวีท"},{"english":"and","thai":"แอนด์"},{"english":"delicious!","thai":"ดิลิเชียส!"}]]$$::jsonb,
'อาหารที่ฉันชอบที่สุดคือผัดไทย มันเผ็ดนิดหน่อยและเปรี้ยว ฉันยังชอบข้าวเหนียวมะม่วงด้วย มันหวานและอร่อย!',
'Thai food spread - pad thai and mango sticky rice, colorful and appetizing cartoon style',
$$[{"question":"\"Spicy\" แปลว่าอะไร?","options":["หวาน","เปรี้ยว","เผ็ด","เค็ม"],"correctIndex":2,"type":"vocab"},{"question":"\"Sweet\" แปลว่าอะไร?","options":["เผ็ด","เปรี้ยว","เค็ม","หวาน"],"correctIndex":3,"type":"vocab"},{"question":"อาหารที่ฉันชอบที่สุดคืออะไร?","options":["fried rice","pad thai","tom yum","green curry"],"correctIndex":1,"type":"comprehension"},{"question":"ข้าวเหนียวมะม่วงมีรสชาติยังไง?","options":["spicy and sour","salty and bitter","sweet and delicious","sour and salty"],"correctIndex":2,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-food', 'Favorite Food'),

-- ==========================================
-- Module: core-a1-places (5 lessons)
-- ==========================================

-- Lesson 1
(1, 1, 'Places in Town', 'สถานที่ในเมือง',
$$[{"word":"school","phonetic":"สคูล","meaning":"โรงเรียน","partOfSpeech":"n."},{"word":"hospital","phonetic":"ฮอสพิทัล","meaning":"โรงพยาบาล","partOfSpeech":"n."},{"word":"market","phonetic":"มาร์เก็ท","meaning":"ตลาด","partOfSpeech":"n."},{"word":"park","phonetic":"พาร์ค","meaning":"สวนสาธารณะ","partOfSpeech":"n."},{"word":"bank","phonetic":"แบงค์","meaning":"ธนาคาร","partOfSpeech":"n."},{"word":"near","phonetic":"เนียร์","meaning":"ใกล้","partOfSpeech":"prep."}]$$::jsonb,
$$[[{"english":"There","thai":"แดร์"},{"english":"is","thai":"อิส"},{"english":"a","thai":"อะ"},{"english":"school","thai":"สคูล"},{"english":"near","thai":"เนียร์"},{"english":"my","thai":"มาย"},{"english":"house.","thai":"เฮาส์"}],[{"english":"The","thai":"เดอะ"},{"english":"hospital","thai":"ฮอสพิทัล"},{"english":"is","thai":"อิส"},{"english":"on","thai":"ออน"},{"english":"Main","thai":"เมน"},{"english":"Street.","thai":"สตรีท"}],[{"english":"I","thai":"ไอ"},{"english":"go","thai":"โก"},{"english":"to","thai":"ทู"},{"english":"the","thai":"เดอะ"},{"english":"market","thai":"มาร์เก็ท"},{"english":"with","thai":"วิธ"},{"english":"my","thai":"มาย"},{"english":"mom.","thai":"มัม"}],[{"english":"The","thai":"เดอะ"},{"english":"park","thai":"พาร์ค"},{"english":"is","thai":"อิส"},{"english":"big","thai":"บิก"},{"english":"and","thai":"แอนด์"},{"english":"beautiful.","thai":"บิวทิฟูล"}]]$$::jsonb,
'มีโรงเรียนใกล้บ้านของฉัน โรงพยาบาลอยู่บนถนนเมน ฉันไปตลาดกับแม่ สวนสาธารณะใหญ่และสวยงาม',
'Cartoon town map showing school, hospital, market, park, bank, colorful and clear',
$$[{"question":"\"Hospital\" แปลว่าอะไร?","options":["โรงเรียน","โรงพยาบาล","ธนาคาร","ตลาด"],"correctIndex":1,"type":"vocab"},{"question":"\"Near\" แปลว่าอะไร?","options":["ไกล","ใกล้","ข้างๆ","ตรงข้าม"],"correctIndex":1,"type":"vocab"},{"question":"อะไรอยู่ใกล้บ้านของฉัน?","options":["hospital","market","school","bank"],"correctIndex":2,"type":"comprehension"},{"question":"สวนสาธารณะเป็นยังไง?","options":["small and old","big and beautiful","near and cheap","far and quiet"],"correctIndex":1,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-places', 'Places in Town'),

-- Lesson 2
(1, 2, 'How Do I Get There?', 'ไปยังไง?',
$$[{"word":"turn left","phonetic":"เทิร์น เลฟท์","meaning":"เลี้ยวซ้าย","partOfSpeech":"phr."},{"word":"turn right","phonetic":"เทิร์น ไรท์","meaning":"เลี้ยวขวา","partOfSpeech":"phr."},{"word":"go straight","phonetic":"โก สเตรท","meaning":"ตรงไป","partOfSpeech":"phr."},{"word":"next to","phonetic":"เน็กซ์ ทู","meaning":"ข้างๆ","partOfSpeech":"prep."},{"word":"across from","phonetic":"อะครอส ฟรอม","meaning":"ตรงข้าม","partOfSpeech":"prep."},{"word":"excuse me","phonetic":"อิกซ์คิวส์ มี","meaning":"ขอโทษนะ","partOfSpeech":"phr."}]$$::jsonb,
$$[[{"english":"\"Excuse","thai":"\"อิกซ์คิวส์"},{"english":"me,","thai":"มี,"},{"english":"where","thai":"แวร์"},{"english":"is","thai":"อิส"},{"english":"the","thai":"เดอะ"},{"english":"bank?\"","thai":"แบงค์?\""}],[{"english":"\"Go","thai":"\"โก"},{"english":"straight","thai":"สเตรท"},{"english":"and","thai":"แอนด์"},{"english":"turn","thai":"เทิร์น"},{"english":"right.\"","thai":"ไรท์\""}],[{"english":"\"Is","thai":"\"อิส"},{"english":"it","thai":"อิท"},{"english":"next","thai":"เน็กซ์"},{"english":"to","thai":"ทู"},{"english":"the","thai":"เดอะ"},{"english":"school?\"","thai":"สคูล?\""}],[{"english":"\"Yes,","thai":"\"เยส,"},{"english":"it","thai":"อิท"},{"english":"is","thai":"อิส"},{"english":"across","thai":"อะครอส"},{"english":"from","thai":"ฟรอม"},{"english":"the","thai":"เดอะ"},{"english":"park.\"","thai":"พาร์ค\""}]]$$::jsonb,
'"ขอโทษนะ ธนาคารอยู่ที่ไหน?" "ตรงไปแล้วเลี้ยวขวา" "อยู่ข้างๆ โรงเรียนไหม?" "ใช่ อยู่ตรงข้ามสวนสาธารณะ"',
'Cartoon street map with person asking for directions, clear arrows and landmarks',
$$[{"question":"\"Turn right\" แปลว่าอะไร?","options":["เลี้ยวซ้าย","ตรงไป","เลี้ยวขวา","หยุด"],"correctIndex":2,"type":"vocab"},{"question":"\"Next to\" แปลว่าอะไร?","options":["ตรงข้าม","ไกลจาก","ข้างๆ","หลัง"],"correctIndex":2,"type":"vocab"},{"question":"ธนาคารอยู่ที่ไหน?","options":["turn left","go straight and turn right","next to the park","across from the school"],"correctIndex":1,"type":"comprehension"},{"question":"ธนาคารอยู่ตรงข้ามอะไร?","options":["school","hospital","market","park"],"correctIndex":3,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-places', 'Giving Directions'),

-- Lesson 3
(1, 3, 'At the Market', 'ที่ตลาด',
$$[{"word":"buy","phonetic":"บาย","meaning":"ซื้อ","partOfSpeech":"v."},{"word":"sell","phonetic":"เซล","meaning":"ขาย","partOfSpeech":"v."},{"word":"fresh","phonetic":"เฟรช","meaning":"สด","partOfSpeech":"adj."},{"word":"kilo","phonetic":"คิโล","meaning":"กิโลกรัม","partOfSpeech":"n."},{"word":"bag","phonetic":"แบก","meaning":"ถุง","partOfSpeech":"n."},{"word":"change","phonetic":"เชนจ์","meaning":"เงินทอน","partOfSpeech":"n."}]$$::jsonb,
$$[[{"english":"I","thai":"ไอ"},{"english":"go","thai":"โก"},{"english":"to","thai":"ทู"},{"english":"the","thai":"เดอะ"},{"english":"market","thai":"มาร์เก็ท"},{"english":"every","thai":"เอฟรี"},{"english":"morning.","thai":"มอร์นิง"}],[{"english":"I","thai":"ไอ"},{"english":"buy","thai":"บาย"},{"english":"fresh","thai":"เฟรช"},{"english":"vegetables.","thai":"เวจิทะเบิลส์"}],[{"english":"\"How","thai":"\"ฮาว"},{"english":"much","thai":"มัช"},{"english":"for","thai":"ฟอร์"},{"english":"one","thai":"วัน"},{"english":"kilo?\"","thai":"คิโล?\""}],[{"english":"\"Twenty","thai":"\"ทเวนตี"},{"english":"baht.","thai":"บาท"},{"english":"Here","thai":"เฮียร์"},{"english":"is","thai":"อิส"},{"english":"your","thai":"ยัวร์"},{"english":"change.\"","thai":"เชนจ์\""}]]$$::jsonb,
'ฉันไปตลาดทุกเช้า ฉันซื้อผักสด "กิโลละเท่าไหร่?" "ยี่สิบบาท นี่เงินทอนของคุณ"',
'Colorful Thai morning market scene, fresh produce, cartoon style',
$$[{"question":"\"Fresh\" แปลว่าอะไร?","options":["แห้ง","สด","แช่แข็ง","เก่า"],"correctIndex":1,"type":"vocab"},{"question":"\"Change\" ในที่นี้แปลว่าอะไร?","options":["เปลี่ยน","เงินทอน","แลกเปลี่ยน","ราคา"],"correctIndex":1,"type":"vocab"},{"question":"ฉันไปตลาดเมื่อไหร่?","options":["every evening","every afternoon","every morning","every night"],"correctIndex":2,"type":"comprehension"},{"question":"ผักราคากิโลละเท่าไหร่?","options":["10 baht","15 baht","20 baht","25 baht"],"correctIndex":2,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-places', 'At the Market'),

-- Lesson 4
(1, 4, 'At the Library', 'ที่ห้องสมุด',
$$[{"word":"library","phonetic":"ไลบรารี","meaning":"ห้องสมุด","partOfSpeech":"n."},{"word":"book","phonetic":"บุ๊ค","meaning":"หนังสือ","partOfSpeech":"n."},{"word":"borrow","phonetic":"บอร์โรว์","meaning":"ยืม","partOfSpeech":"v."},{"word":"return","phonetic":"รีเทิร์น","meaning":"คืน","partOfSpeech":"v."},{"word":"quiet","phonetic":"ควายเอท","meaning":"เงียบ","partOfSpeech":"adj."},{"word":"shelf","phonetic":"เชลฟ์","meaning":"ชั้นวางหนังสือ","partOfSpeech":"n."}]$$::jsonb,
$$[[{"english":"The","thai":"เดอะ"},{"english":"library","thai":"ไลบรารี"},{"english":"is","thai":"อิส"},{"english":"a","thai":"อะ"},{"english":"quiet","thai":"ควายเอท"},{"english":"place.","thai":"เพลส"}],[{"english":"I","thai":"ไอ"},{"english":"borrow","thai":"บอร์โรว์"},{"english":"books","thai":"บุ๊คส์"},{"english":"from","thai":"ฟรอม"},{"english":"the","thai":"เดอะ"},{"english":"shelf.","thai":"เชลฟ์"}],[{"english":"I","thai":"ไอ"},{"english":"must","thai":"มัสท์"},{"english":"return","thai":"รีเทิร์น"},{"english":"them","thai":"เดม"},{"english":"in","thai":"อิน"},{"english":"two","thai":"ทู"},{"english":"weeks.","thai":"วีคส์"}],[{"english":"I","thai":"ไอ"},{"english":"love","thai":"ลัฟ"},{"english":"reading","thai":"รีดิง"},{"english":"here!","thai":"เฮียร์!"}]]$$::jsonb,
'ห้องสมุดเป็นสถานที่เงียบ ฉันยืมหนังสือจากชั้นวาง ฉันต้องคืนภายในสองสัปดาห์ ฉันชอบอ่านหนังสือที่นี่!',
'Cozy library with bookshelves, child reading, quiet atmosphere, cartoon style',
$$[{"question":"\"Borrow\" แปลว่าอะไร?","options":["ซื้อ","ยืม","คืน","ขาย"],"correctIndex":1,"type":"vocab"},{"question":"\"Quiet\" แปลว่าอะไร?","options":["เสียงดัง","สนุก","เงียบ","ยุ่ง"],"correctIndex":2,"type":"vocab"},{"question":"ห้องสมุดเป็นสถานที่แบบไหน?","options":["noisy","busy","quiet","crowded"],"correctIndex":2,"type":"comprehension"},{"question":"ฉันต้องคืนหนังสือภายในกี่สัปดาห์?","options":["one","two","three","four"],"correctIndex":1,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-places', 'At the Library'),

-- Lesson 5
(1, 5, 'My Neighborhood', 'ย่านบ้านของฉัน',
$$[{"word":"neighborhood","phonetic":"เนเบอร์ฮูด","meaning":"ย่าน/ละแวกบ้าน","partOfSpeech":"n."},{"word":"house","phonetic":"เฮาส์","meaning":"บ้าน","partOfSpeech":"n."},{"word":"street","phonetic":"สตรีท","meaning":"ถนน","partOfSpeech":"n."},{"word":"neighbor","phonetic":"เนเบอร์","meaning":"เพื่อนบ้าน","partOfSpeech":"n."},{"word":"safe","phonetic":"เซฟ","meaning":"ปลอดภัย","partOfSpeech":"adj."},{"word":"friendly","phonetic":"เฟรนด์ลี","meaning":"เป็นมิตร","partOfSpeech":"adj."}]$$::jsonb,
$$[[{"english":"I","thai":"ไอ"},{"english":"live","thai":"ลิฟ"},{"english":"in","thai":"อิน"},{"english":"a","thai":"อะ"},{"english":"nice","thai":"ไนซ์"},{"english":"neighborhood.","thai":"เนเบอร์ฮูด"}],[{"english":"My","thai":"มาย"},{"english":"street","thai":"สตรีท"},{"english":"is","thai":"อิส"},{"english":"clean","thai":"คลีน"},{"english":"and","thai":"แอนด์"},{"english":"safe.","thai":"เซฟ"}],[{"english":"My","thai":"มาย"},{"english":"neighbors","thai":"เนเบอร์ส"},{"english":"are","thai":"อาร์"},{"english":"very","thai":"เวรี"},{"english":"friendly.","thai":"เฟรนด์ลี"}],[{"english":"I","thai":"ไอ"},{"english":"love","thai":"ลัฟ"},{"english":"my","thai":"มาย"},{"english":"neighborhood!","thai":"เนเบอร์ฮูด!"}]]$$::jsonb,
'ฉันอาศัยอยู่ในย่านที่ดี ถนนของฉันสะอาดและปลอดภัย เพื่อนบ้านของฉันเป็นมิตรมาก ฉันรักย่านบ้านของฉัน!',
'Cartoon neighborhood with houses, clean streets, friendly neighbors waving, sunny day',
$$[{"question":"\"Neighbor\" แปลว่าอะไร?","options":["เพื่อน","เพื่อนบ้าน","ครอบครัว","คนแปลกหน้า"],"correctIndex":1,"type":"vocab"},{"question":"\"Safe\" แปลว่าอะไร?","options":["สกปรก","อันตราย","ปลอดภัย","เงียบ"],"correctIndex":2,"type":"vocab"},{"question":"ถนนของฉันเป็นยังไง?","options":["dirty and dangerous","clean and safe","noisy and busy","old and broken"],"correctIndex":1,"type":"comprehension"},{"question":"เพื่อนบ้านของฉันเป็นยังไง?","options":["unfriendly","quiet","very friendly","busy"],"correctIndex":2,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-places', 'My Neighborhood'),

-- ==========================================
-- Module: core-a1-shopping (5 lessons)
-- ==========================================

-- Lesson 1
(1, 1, 'Let''s Go Shopping!', 'ไปช้อปปิ้งกัน!',
$$[{"word":"shop","phonetic":"ช็อป","meaning":"ร้านค้า/ช้อปปิ้ง","partOfSpeech":"n./v."},{"word":"store","phonetic":"สตอร์","meaning":"ร้านค้า","partOfSpeech":"n."},{"word":"buy","phonetic":"บาย","meaning":"ซื้อ","partOfSpeech":"v."},{"word":"pay","phonetic":"เพย์","meaning":"จ่าย","partOfSpeech":"v."},{"word":"cash","phonetic":"แคช","meaning":"เงินสด","partOfSpeech":"n."},{"word":"receipt","phonetic":"รีซีท","meaning":"ใบเสร็จ","partOfSpeech":"n."}]$$::jsonb,
$$[[{"english":"Let''s","thai":"เลทส์"},{"english":"go","thai":"โก"},{"english":"shopping!","thai":"ช็อปปิ้ง!"}],[{"english":"I","thai":"ไอ"},{"english":"need","thai":"นีด"},{"english":"to","thai":"ทู"},{"english":"buy","thai":"บาย"},{"english":"new","thai":"นิว"},{"english":"shoes.","thai":"ชูส์"}],[{"english":"I","thai":"ไอ"},{"english":"pay","thai":"เพย์"},{"english":"with","thai":"วิธ"},{"english":"cash.","thai":"แคช"}],[{"english":"The","thai":"เดอะ"},{"english":"cashier","thai":"แคชเชียร์"},{"english":"gives","thai":"กิฟส์"},{"english":"me","thai":"มี"},{"english":"a","thai":"อะ"},{"english":"receipt.","thai":"รีซีท"}]]$$::jsonb,
'ไปช้อปปิ้งกัน! ฉันต้องซื้อรองเท้าใหม่ ฉันจ่ายด้วยเงินสด แคชเชียร์ให้ใบเสร็จฉัน',
'Cartoon shopping scene in a store, buying shoes, paying at counter, bright and colorful',
$$[{"question":"\"Pay\" แปลว่าอะไร?","options":["ซื้อ","ขาย","จ่าย","รับ"],"correctIndex":2,"type":"vocab"},{"question":"\"Receipt\" แปลว่าอะไร?","options":["เงินสด","บัตรเครดิต","ใบเสร็จ","ส่วนลด"],"correctIndex":2,"type":"vocab"},{"question":"ฉันต้องซื้ออะไร?","options":["new shirt","new bag","new shoes","new hat"],"correctIndex":2,"type":"comprehension"},{"question":"ฉันจ่ายด้วยอะไร?","options":["credit card","cash","phone","check"],"correctIndex":1,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-shopping', 'Shopping Basics'),

-- Lesson 2
(1, 2, 'Clothes and Sizes', 'เสื้อผ้าและไซส์',
$$[{"word":"shirt","phonetic":"เชิร์ท","meaning":"เสื้อเชิ้ต","partOfSpeech":"n."},{"word":"pants","phonetic":"แพนทส์","meaning":"กางเกง","partOfSpeech":"n."},{"word":"dress","phonetic":"เดรส","meaning":"ชุดเดรส","partOfSpeech":"n."},{"word":"size","phonetic":"ไซส์","meaning":"ขนาด/ไซส์","partOfSpeech":"n."},{"word":"try on","phonetic":"ทราย ออน","meaning":"ลองใส่","partOfSpeech":"phr."},{"word":"fit","phonetic":"ฟิท","meaning":"พอดี","partOfSpeech":"v./adj."}]$$::jsonb,
$$[[{"english":"I","thai":"ไอ"},{"english":"want","thai":"วอนท์"},{"english":"to","thai":"ทู"},{"english":"buy","thai":"บาย"},{"english":"a","thai":"อะ"},{"english":"shirt.","thai":"เชิร์ท"}],[{"english":"\"What","thai":"\"ว็อท"},{"english":"size","thai":"ไซส์"},{"english":"do","thai":"ดู"},{"english":"you","thai":"ยู"},{"english":"need?\"","thai":"นีด?\""}],[{"english":"\"Medium,","thai":"\"มีเดียม,"},{"english":"please.","thai":"พลีส"},{"english":"Can","thai":"แคน"},{"english":"I","thai":"ไอ"},{"english":"try","thai":"ทราย"},{"english":"it","thai":"อิท"},{"english":"on?\"","thai":"ออน?\""}],[{"english":"\"It","thai":"\"อิท"},{"english":"fits","thai":"ฟิทส์"},{"english":"perfectly!\"","thai":"เพอร์เฟคลี!\""}]]$$::jsonb,
'ฉันอยากซื้อเสื้อเชิ้ต "คุณต้องการไซส์อะไร?" "ไซส์กลางครับ ขอลองได้ไหม?" "พอดีมาก!"',
'Clothing store scene, trying on clothes, cartoon style, colorful clothes on display',
$$[{"question":"\"Size\" แปลว่าอะไร?","options":["สี","ราคา","ขนาด/ไซส์","แบบ"],"correctIndex":2,"type":"vocab"},{"question":"\"Try on\" แปลว่าอะไร?","options":["ซื้อ","ลองใส่","คืน","เลือก"],"correctIndex":1,"type":"vocab"},{"question":"ฉันต้องการไซส์อะไร?","options":["small","medium","large","extra large"],"correctIndex":1,"type":"comprehension"},{"question":"เสื้อเป็นยังไง?","options":["too big","too small","fits perfectly","too expensive"],"correctIndex":2,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-shopping', 'Clothes Shopping'),

-- Lesson 3
(1, 3, 'At the Supermarket', 'ที่ซูเปอร์มาร์เก็ต',
$$[{"word":"supermarket","phonetic":"ซูเปอร์มาร์เก็ท","meaning":"ซูเปอร์มาร์เก็ต","partOfSpeech":"n."},{"word":"aisle","phonetic":"ไอล์","meaning":"ทางเดินระหว่างชั้น","partOfSpeech":"n."},{"word":"cart","phonetic":"คาร์ท","meaning":"รถเข็น","partOfSpeech":"n."},{"word":"list","phonetic":"ลิสท์","meaning":"รายการ","partOfSpeech":"n."},{"word":"discount","phonetic":"ดิสเคานท์","meaning":"ส่วนลด","partOfSpeech":"n."},{"word":"checkout","phonetic":"เช็คเอาท์","meaning":"แคชเชียร์/จุดชำระเงิน","partOfSpeech":"n."}]$$::jsonb,
$$[[{"english":"I","thai":"ไอ"},{"english":"go","thai":"โก"},{"english":"to","thai":"ทู"},{"english":"the","thai":"เดอะ"},{"english":"supermarket","thai":"ซูเปอร์มาร์เก็ท"},{"english":"with","thai":"วิธ"},{"english":"a","thai":"อะ"},{"english":"list.","thai":"ลิสท์"}],[{"english":"I","thai":"ไอ"},{"english":"push","thai":"พุช"},{"english":"a","thai":"อะ"},{"english":"cart","thai":"คาร์ท"},{"english":"through","thai":"ทรู"},{"english":"the","thai":"เดอะ"},{"english":"aisles.","thai":"ไอล์ส"}],[{"english":"This","thai":"ดิส"},{"english":"item","thai":"ไอเทม"},{"english":"has","thai":"แฮส"},{"english":"a","thai":"อะ"},{"english":"discount!","thai":"ดิสเคานท์!"}],[{"english":"I","thai":"ไอ"},{"english":"pay","thai":"เพย์"},{"english":"at","thai":"แอท"},{"english":"the","thai":"เดอะ"},{"english":"checkout.","thai":"เช็คเอาท์"}]]$$::jsonb,
'ฉันไปซูเปอร์มาร์เก็ตพร้อมรายการ ฉันเข็นรถเข็นผ่านทางเดิน สินค้านี้มีส่วนลด! ฉันจ่ายที่แคชเชียร์',
'Supermarket interior with shopping cart, aisles, discount signs, cartoon style',
$$[{"question":"\"Cart\" แปลว่าอะไร?","options":["ตะกร้า","ถุง","รถเข็น","กล่อง"],"correctIndex":2,"type":"vocab"},{"question":"\"Discount\" แปลว่าอะไร?","options":["ราคาเต็ม","ส่วนลด","ภาษี","ค่าบริการ"],"correctIndex":1,"type":"vocab"},{"question":"ฉันไปซูเปอร์มาร์เก็ตพร้อมอะไร?","options":["a friend","a cart","a list","a bag"],"correctIndex":2,"type":"comprehension"},{"question":"ฉันจ่ายเงินที่ไหน?","options":["the entrance","the aisle","the checkout","the exit"],"correctIndex":2,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-shopping', 'Supermarket'),

-- Lesson 4
(1, 4, 'Can I Help You?', 'ให้ช่วยอะไรได้ไหม?',
$$[{"word":"help","phonetic":"เฮลป์","meaning":"ช่วย","partOfSpeech":"v."},{"word":"looking for","phonetic":"ลุคกิง ฟอร์","meaning":"กำลังหา","partOfSpeech":"phr."},{"word":"sold out","phonetic":"โซลด์ เอาท์","meaning":"หมดแล้ว","partOfSpeech":"phr."},{"word":"available","phonetic":"อะเวเลเบิล","meaning":"มีอยู่","partOfSpeech":"adj."},{"word":"color","phonetic":"คัลเลอร์","meaning":"สี","partOfSpeech":"n."},{"word":"exchange","phonetic":"อิกซ์เชนจ์","meaning":"แลกเปลี่ยน","partOfSpeech":"v."}]$$::jsonb,
$$[[{"english":"\"Can","thai":"\"แคน"},{"english":"I","thai":"ไอ"},{"english":"help","thai":"เฮลป์"},{"english":"you?\"","thai":"ยู?\""}],[{"english":"\"I","thai":"\"ไอ"},{"english":"am","thai":"แอม"},{"english":"looking","thai":"ลุคกิง"},{"english":"for","thai":"ฟอร์"},{"english":"a","thai":"อะ"},{"english":"blue","thai":"บลู"},{"english":"bag.\"","thai":"แบก\""}],[{"english":"\"Sorry,","thai":"\"ซอร์รี,"},{"english":"the","thai":"เดอะ"},{"english":"blue","thai":"บลู"},{"english":"one","thai":"วัน"},{"english":"is","thai":"อิส"},{"english":"sold","thai":"โซลด์"},{"english":"out.\"","thai":"เอาท์\""}],[{"english":"\"Is","thai":"\"อิส"},{"english":"the","thai":"เดอะ"},{"english":"red","thai":"เรด"},{"english":"one","thai":"วัน"},{"english":"available?\"","thai":"อะเวเลเบิล?\""}],[{"english":"\"Yes!","thai":"\"เยส!"},{"english":"Here","thai":"เฮียร์"},{"english":"you","thai":"ยู"},{"english":"go!\"","thai":"โก!\""}]]$$::jsonb,
'"ให้ช่วยอะไรได้ไหม?" "ฉันกำลังหากระเป๋าสีน้ำเงิน" "ขอโทษ สีน้ำเงินหมดแล้ว" "สีแดงมีไหม?" "มีครับ! นี่เลย!"',
'Shop assistant helping customer find a bag, cartoon style, friendly store atmosphere',
$$[{"question":"\"Sold out\" แปลว่าอะไร?","options":["ลดราคา","หมดแล้ว","มีอยู่","ใหม่"],"correctIndex":1,"type":"vocab"},{"question":"\"Looking for\" แปลว่าอะไร?","options":["ซื้อ","กำลังหา","ขาย","คืน"],"correctIndex":1,"type":"vocab"},{"question":"ลูกค้าต้องการกระเป๋าสีอะไร?","options":["red","green","blue","yellow"],"correctIndex":2,"type":"comprehension"},{"question":"สุดท้ายลูกค้าได้กระเป๋าสีอะไร?","options":["blue","green","red","yellow"],"correctIndex":2,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-shopping', 'Shopping Dialogue'),

-- Lesson 5
(1, 5, 'Online Shopping', 'ช้อปปิ้งออนไลน์',
$$[{"word":"online","phonetic":"ออนไลน์","meaning":"ออนไลน์","partOfSpeech":"adj."},{"word":"website","phonetic":"เว็บไซต์","meaning":"เว็บไซต์","partOfSpeech":"n."},{"word":"delivery","phonetic":"ดิลิเวอรี","meaning":"การจัดส่ง","partOfSpeech":"n."},{"word":"order","phonetic":"ออร์เดอร์","meaning":"สั่งซื้อ","partOfSpeech":"v."},{"word":"package","phonetic":"แพ็คเกจ","meaning":"พัสดุ","partOfSpeech":"n."},{"word":"arrive","phonetic":"อะไรฟ์","meaning":"มาถึง","partOfSpeech":"v."}]$$::jsonb,
$$[[{"english":"I","thai":"ไอ"},{"english":"shop","thai":"ช็อป"},{"english":"online","thai":"ออนไลน์"},{"english":"sometimes.","thai":"ซัมไทมส์"}],[{"english":"I","thai":"ไอ"},{"english":"find","thai":"ไฟนด์"},{"english":"a","thai":"อะ"},{"english":"book","thai":"บุ๊ค"},{"english":"on","thai":"ออน"},{"english":"a","thai":"อะ"},{"english":"website.","thai":"เว็บไซต์"}],[{"english":"I","thai":"ไอ"},{"english":"order","thai":"ออร์เดอร์"},{"english":"it","thai":"อิท"},{"english":"and","thai":"แอนด์"},{"english":"wait","thai":"เวท"},{"english":"for","thai":"ฟอร์"},{"english":"delivery.","thai":"ดิลิเวอรี"}],[{"english":"The","thai":"เดอะ"},{"english":"package","thai":"แพ็คเกจ"},{"english":"arrives","thai":"อะไรฟ์ส"},{"english":"in","thai":"อิน"},{"english":"two","thai":"ทู"},{"english":"days!","thai":"เดย์ส!"}]]$$::jsonb,
'บางครั้งฉันช้อปปิ้งออนไลน์ ฉันเจอหนังสือในเว็บไซต์ ฉันสั่งซื้อและรอการจัดส่ง พัสดุมาถึงในสองวัน!',
'Cartoon child shopping online on tablet, package arriving at door, happy expression',
$$[{"question":"\"Delivery\" แปลว่าอะไร?","options":["การสั่งซื้อ","การจัดส่ง","การคืนสินค้า","การชำระเงิน"],"correctIndex":1,"type":"vocab"},{"question":"\"Arrive\" แปลว่าอะไร?","options":["ออกเดินทาง","รอ","มาถึง","ส่ง"],"correctIndex":2,"type":"vocab"},{"question":"ฉันสั่งซื้ออะไร?","options":["clothes","shoes","a book","a bag"],"correctIndex":2,"type":"comprehension"},{"question":"พัสดุมาถึงในกี่วัน?","options":["one","two","three","four"],"correctIndex":1,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-shopping', 'Online Shopping'),

-- ==========================================
-- Module: core-a1-conversation (6 lessons)
-- ==========================================

-- Lesson 1
(1, 1, 'Can You Speak English?', 'คุณพูดภาษาอังกฤษได้ไหม?',
$$[{"word":"speak","phonetic":"สพีค","meaning":"พูด","partOfSpeech":"v."},{"word":"understand","phonetic":"อันเดอร์สแตนด์","meaning":"เข้าใจ","partOfSpeech":"v."},{"word":"slowly","phonetic":"สโลวลี","meaning":"ช้าๆ","partOfSpeech":"adv."},{"word":"repeat","phonetic":"รีพีท","meaning":"พูดซ้ำ","partOfSpeech":"v."},{"word":"mean","phonetic":"มีน","meaning":"หมายความว่า","partOfSpeech":"v."},{"word":"language","phonetic":"แลงกวิจ","meaning":"ภาษา","partOfSpeech":"n."}]$$::jsonb,
$$[[{"english":"\"Can","thai":"\"แคน"},{"english":"you","thai":"ยู"},{"english":"speak","thai":"สพีค"},{"english":"English?\"","thai":"อิงลิช?\""}],[{"english":"\"Yes,","thai":"\"เยส,"},{"english":"a","thai":"อะ"},{"english":"little.\"","thai":"ลิทเทิล\""}],[{"english":"\"Please","thai":"\"พลีส"},{"english":"speak","thai":"สพีค"},{"english":"slowly.\"","thai":"สโลวลี\""}],[{"english":"\"Can","thai":"\"แคน"},{"english":"you","thai":"ยู"},{"english":"repeat","thai":"รีพีท"},{"english":"that?\"","thai":"แดท?\""}],[{"english":"\"What","thai":"\"ว็อท"},{"english":"does","thai":"ดัส"},{"english":"that","thai":"แดท"},{"english":"mean?\"","thai":"มีน?\""}]]$$::jsonb,
'"คุณพูดภาษาอังกฤษได้ไหม?" "ได้นิดหน่อย" "กรุณาพูดช้าๆ" "พูดซ้ำได้ไหม?" "นั่นหมายความว่าอะไร?"',
'Two people having a conversation, one asking for help with language, friendly cartoon style',
$$[{"question":"\"Understand\" แปลว่าอะไร?","options":["พูด","ฟัง","เข้าใจ","อ่าน"],"correctIndex":2,"type":"vocab"},{"question":"\"Slowly\" แปลว่าอะไร?","options":["เร็วๆ","ช้าๆ","ดังๆ","เบาๆ"],"correctIndex":1,"type":"vocab"},{"question":"คนพูดภาษาอังกฤษได้แค่ไหน?","options":["very well","fluently","a little","not at all"],"correctIndex":2,"type":"comprehension"},{"question":"\"Repeat\" แปลว่าอะไร?","options":["หยุด","เริ่ม","พูดซ้ำ","เปลี่ยน"],"correctIndex":2,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-conversation', 'Speaking English'),

-- Lesson 2
(1, 2, 'Making Plans', 'วางแผน',
$$[{"word":"plan","phonetic":"แพลน","meaning":"แผน/วางแผน","partOfSpeech":"n./v."},{"word":"want to","phonetic":"วอนท์ ทู","meaning":"อยากจะ","partOfSpeech":"phr."},{"word":"let''s","phonetic":"เลทส์","meaning":"มา...กันเถอะ","partOfSpeech":"phr."},{"word":"sounds good","phonetic":"เซานดส์ กู๊ด","meaning":"ฟังดูดี","partOfSpeech":"phr."},{"word":"meet","phonetic":"มีท","meaning":"พบ/นัดพบ","partOfSpeech":"v."},{"word":"where","phonetic":"แวร์","meaning":"ที่ไหน","partOfSpeech":"adv."}]$$::jsonb,
$$[[{"english":"\"What","thai":"\"ว็อท"},{"english":"do","thai":"ดู"},{"english":"you","thai":"ยู"},{"english":"want","thai":"วอนท์"},{"english":"to","thai":"ทู"},{"english":"do","thai":"ดู"},{"english":"today?\"","thai":"ทูเดย์?\""}],[{"english":"\"Let''s","thai":"\"เลทส์"},{"english":"go","thai":"โก"},{"english":"to","thai":"ทู"},{"english":"the","thai":"เดอะ"},{"english":"park!\"","thai":"พาร์ค!\""}],[{"english":"\"Sounds","thai":"\"เซานดส์"},{"english":"good!","thai":"กู๊ด!"},{"english":"Where","thai":"แวร์"},{"english":"shall","thai":"แชล"},{"english":"we","thai":"วี"},{"english":"meet?\"","thai":"มีท?\""}],[{"english":"\"Let''s","thai":"\"เลทส์"},{"english":"meet","thai":"มีท"},{"english":"at","thai":"แอท"},{"english":"the","thai":"เดอะ"},{"english":"gate","thai":"เกท"},{"english":"at","thai":"แอท"},{"english":"ten.\"","thai":"เทน\""}]]$$::jsonb,
'"วันนี้อยากทำอะไร?" "ไปสวนสาธารณะกันเถอะ!" "ฟังดูดี! จะนัดพบที่ไหน?" "นัดพบที่ประตูตอนสิบโมง"',
'Two friends making plans to go to the park, cartoon style, cheerful atmosphere',
$$[{"question":"\"Let''s\" แปลว่าอะไร?","options":["ฉัน","คุณ","มา...กันเถอะ","พวกเขา"],"correctIndex":2,"type":"vocab"},{"question":"\"Sounds good\" แปลว่าอะไร?","options":["ฟังดูแย่","ฟังดูดี","ไม่แน่ใจ","บางที"],"correctIndex":1,"type":"vocab"},{"question":"พวกเขาจะไปที่ไหน?","options":["market","school","park","library"],"correctIndex":2,"type":"comprehension"},{"question":"พวกเขานัดพบกี่โมง?","options":["nine","ten","eleven","twelve"],"correctIndex":1,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-conversation', 'Making Plans'),

-- Lesson 3
(1, 3, 'Asking for Help', 'ขอความช่วยเหลือ',
$$[{"word":"help","phonetic":"เฮลป์","meaning":"ช่วย","partOfSpeech":"v."},{"word":"problem","phonetic":"พรอบเลม","meaning":"ปัญหา","partOfSpeech":"n."},{"word":"lost","phonetic":"ลอสท์","meaning":"หลงทาง","partOfSpeech":"adj."},{"word":"find","phonetic":"ไฟนด์","meaning":"หา/พบ","partOfSpeech":"v."},{"word":"way","phonetic":"เวย์","meaning":"ทาง","partOfSpeech":"n."},{"word":"of course","phonetic":"อ็อฟ คอร์ส","meaning":"แน่นอน","partOfSpeech":"phr."}]$$::jsonb,
$$[[{"english":"\"Excuse","thai":"\"อิกซ์คิวส์"},{"english":"me,","thai":"มี,"},{"english":"can","thai":"แคน"},{"english":"you","thai":"ยู"},{"english":"help","thai":"เฮลป์"},{"english":"me?\"","thai":"มี?\""}],[{"english":"\"Of","thai":"\"อ็อฟ"},{"english":"course!","thai":"คอร์ส!"},{"english":"What","thai":"ว็อท"},{"english":"is","thai":"อิส"},{"english":"the","thai":"เดอะ"},{"english":"problem?\"","thai":"พรอบเลม?\""}],[{"english":"\"I","thai":"\"ไอ"},{"english":"am","thai":"แอม"},{"english":"lost.","thai":"ลอสท์"},{"english":"I","thai":"ไอ"},{"english":"cannot","thai":"แคนนอท"},{"english":"find","thai":"ไฟนด์"},{"english":"my","thai":"มาย"},{"english":"way.\"","thai":"เวย์\""}],[{"english":"\"Don''t","thai":"\"โดนท์"},{"english":"worry!","thai":"วอร์รี!"},{"english":"I","thai":"ไอ"},{"english":"will","thai":"วิล"},{"english":"help","thai":"เฮลป์"},{"english":"you.\"","thai":"ยู\""}]]$$::jsonb,
'"ขอโทษนะ ช่วยฉันได้ไหม?" "แน่นอน! มีปัญหาอะไร?" "ฉันหลงทาง หาทางไม่เจอ" "ไม่ต้องกังวล! ฉันจะช่วยคุณ"',
'Person looking lost, kind stranger helping with directions, cartoon style, city street',
$$[{"question":"\"Lost\" แปลว่าอะไร?","options":["พบ","หลงทาง","รู้จัก","จำได้"],"correctIndex":1,"type":"vocab"},{"question":"\"Of course\" แปลว่าอะไร?","options":["บางที","ไม่แน่ใจ","แน่นอน","ขอโทษ"],"correctIndex":2,"type":"vocab"},{"question":"ปัญหาของคนนั้นคืออะไร?","options":["hungry","lost","tired","sick"],"correctIndex":1,"type":"comprehension"},{"question":"คนแปลกหน้าตอบว่าอะไร?","options":["Sorry, I don''t know","Don''t worry, I will help","Go straight","Turn right"],"correctIndex":1,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-conversation', 'Asking for Help'),

-- Lesson 4
(1, 4, 'Talking About the Weather', 'คุยเรื่องอากาศ',
$$[{"word":"weather","phonetic":"เวเธอร์","meaning":"อากาศ","partOfSpeech":"n."},{"word":"sunny","phonetic":"ซันนี","meaning":"แดดออก","partOfSpeech":"adj."},{"word":"rainy","phonetic":"เรนนี","meaning":"ฝนตก","partOfSpeech":"adj."},{"word":"hot","phonetic":"ฮ็อท","meaning":"ร้อน","partOfSpeech":"adj."},{"word":"cold","phonetic":"โคลด์","meaning":"หนาว","partOfSpeech":"adj."},{"word":"today","phonetic":"ทูเดย์","meaning":"วันนี้","partOfSpeech":"n."}]$$::jsonb,
$$[[{"english":"\"How''s","thai":"\"ฮาวส์"},{"english":"the","thai":"เดอะ"},{"english":"weather","thai":"เวเธอร์"},{"english":"today?\"","thai":"ทูเดย์?\""}],[{"english":"\"It","thai":"\"อิท"},{"english":"is","thai":"อิส"},{"english":"sunny","thai":"ซันนี"},{"english":"and","thai":"แอนด์"},{"english":"hot.\"","thai":"ฮ็อท\""}],[{"english":"\"I","thai":"\"ไอ"},{"english":"love","thai":"ลัฟ"},{"english":"sunny","thai":"ซันนี"},{"english":"days!\"","thai":"เดย์ส!\""}],[{"english":"\"Me","thai":"\"มี"},{"english":"too!","thai":"ทู!"},{"english":"Let''s","thai":"เลทส์"},{"english":"go","thai":"โก"},{"english":"outside.\"","thai":"เอาท์ไซด์\""}]]$$::jsonb,
'"วันนี้อากาศเป็นยังไง?" "แดดออกและร้อน" "ฉันชอบวันที่แดดออก!" "ฉันก็เหมือนกัน! ออกไปข้างนอกกันเถอะ"',
'Two friends talking about sunny weather, going outside to play, cartoon style',
$$[{"question":"\"Sunny\" แปลว่าอะไร?","options":["ฝนตก","หิมะตก","แดดออก","มีเมฆ"],"correctIndex":2,"type":"vocab"},{"question":"\"Hot\" แปลว่าอะไร?","options":["หนาว","เย็น","ร้อน","อบอุ่น"],"correctIndex":2,"type":"vocab"},{"question":"วันนี้อากาศเป็นยังไง?","options":["rainy and cold","cloudy and cool","sunny and hot","windy and warm"],"correctIndex":2,"type":"comprehension"},{"question":"พวกเขาจะทำอะไร?","options":["stay inside","watch TV","go outside","sleep"],"correctIndex":2,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-conversation', 'Weather Talk'),

-- Lesson 5
(1, 5, 'Saying Sorry and Thank You', 'ขอโทษและขอบคุณ',
$$[{"word":"sorry","phonetic":"ซอร์รี","meaning":"ขอโทษ","partOfSpeech":"interj."},{"word":"that''s okay","phonetic":"แดทส์ โอเค","meaning":"ไม่เป็นไร","partOfSpeech":"phr."},{"word":"thank you so much","phonetic":"แธงค์ยู โซ มัช","meaning":"ขอบคุณมากๆ","partOfSpeech":"phr."},{"word":"you''re welcome","phonetic":"ยัวร์ เวลคัม","meaning":"ยินดี","partOfSpeech":"phr."},{"word":"my fault","phonetic":"มาย ฟอลท์","meaning":"ความผิดของฉัน","partOfSpeech":"phr."},{"word":"no problem","phonetic":"โน พรอบเลม","meaning":"ไม่มีปัญหา","partOfSpeech":"phr."}]$$::jsonb,
$$[[{"english":"\"Oh","thai":"\"โอ"},{"english":"no!","thai":"โน!"},{"english":"I","thai":"ไอ"},{"english":"am","thai":"แอม"},{"english":"so","thai":"โซ"},{"english":"sorry!\"","thai":"ซอร์รี!\""}],[{"english":"\"That''s","thai":"\"แดทส์"},{"english":"okay.","thai":"โอเค"},{"english":"It","thai":"อิท"},{"english":"is","thai":"อิส"},{"english":"my","thai":"มาย"},{"english":"fault","thai":"ฟอลท์"},{"english":"too.\"","thai":"ทู\""}],[{"english":"\"Thank","thai":"\"แธงค์"},{"english":"you","thai":"ยู"},{"english":"so","thai":"โซ"},{"english":"much","thai":"มัช"},{"english":"for","thai":"ฟอร์"},{"english":"your","thai":"ยัวร์"},{"english":"help!\"","thai":"เฮลป์!\""}],[{"english":"\"You''re","thai":"\"ยัวร์"},{"english":"welcome!","thai":"เวลคัม!"},{"english":"No","thai":"โน"},{"english":"problem!\"","thai":"พรอบเลม!\""}]]$$::jsonb,
'"โอ้ไม่! ขอโทษมากๆ!" "ไม่เป็นไร ความผิดของฉันด้วย" "ขอบคุณมากๆ ที่ช่วย!" "ยินดี! ไม่มีปัญหา!"',
'Two friends apologizing and thanking each other, warm and friendly cartoon style',
$$[{"question":"\"That''s okay\" แปลว่าอะไร?","options":["ขอโทษ","ขอบคุณ","ไม่เป็นไร","ยินดี"],"correctIndex":2,"type":"vocab"},{"question":"\"You''re welcome\" แปลว่าอะไร?","options":["ขอโทษ","ขอบคุณ","ไม่เป็นไร","ยินดี"],"correctIndex":3,"type":"vocab"},{"question":"\"No problem\" แปลว่าอะไร?","options":["มีปัญหา","ไม่มีปัญหา","ขอโทษ","ขอบคุณ"],"correctIndex":1,"type":"comprehension"},{"question":"\"My fault\" แปลว่าอะไร?","options":["ความผิดของคุณ","ความผิดของฉัน","ไม่ใช่ความผิดของใคร","ความผิดของเขา"],"correctIndex":1,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-conversation', 'Apologies and Thanks'),

-- Lesson 6
(1, 6, 'Talking About Yourself', 'เล่าเรื่องตัวเอง',
$$[{"word":"describe","phonetic":"ดิสไครบ์","meaning":"บรรยาย","partOfSpeech":"v."},{"word":"personality","phonetic":"เพอร์ซะแนลิตี","meaning":"บุคลิกภาพ","partOfSpeech":"n."},{"word":"shy","phonetic":"ชาย","meaning":"ขี้อาย","partOfSpeech":"adj."},{"word":"outgoing","phonetic":"เอาท์โกอิง","meaning":"ชอบเข้าสังคม","partOfSpeech":"adj."},{"word":"hardworking","phonetic":"ฮาร์ดเวิร์คกิง","meaning":"ขยัน","partOfSpeech":"adj."},{"word":"creative","phonetic":"ครีเอทิฟ","meaning":"สร้างสรรค์","partOfSpeech":"adj."}]$$::jsonb,
$$[[{"english":"Let","thai":"เลท"},{"english":"me","thai":"มี"},{"english":"tell","thai":"เทล"},{"english":"you","thai":"ยู"},{"english":"about","thai":"อะเบาท์"},{"english":"myself.","thai":"มายเซลฟ์"}],[{"english":"I","thai":"ไอ"},{"english":"am","thai":"แอม"},{"english":"outgoing","thai":"เอาท์โกอิง"},{"english":"and","thai":"แอนด์"},{"english":"creative.","thai":"ครีเอทิฟ"}],[{"english":"I","thai":"ไอ"},{"english":"am","thai":"แอม"},{"english":"also","thai":"ออลโซ"},{"english":"hardworking","thai":"ฮาร์ดเวิร์คกิง"},{"english":"at","thai":"แอท"},{"english":"school.","thai":"สคูล"}],[{"english":"I","thai":"ไอ"},{"english":"love","thai":"ลัฟ"},{"english":"meeting","thai":"มีทิง"},{"english":"new","thai":"นิว"},{"english":"people!","thai":"พีเพิล!"}]]$$::jsonb,
'ให้ฉันเล่าเรื่องตัวเอง ฉันชอบเข้าสังคมและสร้างสรรค์ ฉันยังขยันที่โรงเรียนด้วย ฉันชอบพบปะคนใหม่!',
'Confident cartoon character introducing themselves, speech bubble with personality traits',
$$[{"question":"\"Outgoing\" แปลว่าอะไร?","options":["ขี้อาย","ชอบเข้าสังคม","ขยัน","สร้างสรรค์"],"correctIndex":1,"type":"vocab"},{"question":"\"Hardworking\" แปลว่าอะไร?","options":["ขี้เกียจ","ขยัน","ตลก","ใจดี"],"correctIndex":1,"type":"vocab"},{"question":"ฉันมีบุคลิกแบบไหน?","options":["shy and quiet","outgoing and creative","lazy and boring","serious and strict"],"correctIndex":1,"type":"comprehension"},{"question":"ฉันชอบทำอะไร?","options":["stay home","read books","meet new people","watch TV"],"correctIndex":2,"type":"comprehension"}]$$::jsonb,
true, 'core-a1-conversation', 'About Yourself');
