-- =============================================
-- Seed: Core Pre-A1 (Level 0) — 4 modules, 14 lessons
-- =============================================
SET search_path TO public;
DELETE FROM lessons WHERE module_id LIKE 'core-a0-%';

INSERT INTO lessons (level, lesson_order, title, title_thai, vocabulary, article_sentences, article_translation, image_prompt, quiz, is_published, module_id, topic) VALUES

-- ── core-a0-alphabet (4 lessons) ──

(0,1,'Apple to Gorilla','ตัวอักษร A-G',
'[{"word":"apple","phonetic":"แอปเปิล","meaning":"แอปเปิล","partOfSpeech":"n."},{"word":"ball","phonetic":"บอล","meaning":"ลูกบอล","partOfSpeech":"n."},{"word":"cat","phonetic":"แคท","meaning":"แมว","partOfSpeech":"n."},{"word":"dog","phonetic":"ด็อก","meaning":"หมา","partOfSpeech":"n."},{"word":"egg","phonetic":"เอ็ก","meaning":"ไข่","partOfSpeech":"n."},{"word":"fish","phonetic":"ฟิช","meaning":"ปลา","partOfSpeech":"n."},{"word":"gorilla","phonetic":"กอริลลา","meaning":"กอริลลา","partOfSpeech":"n."}]'::jsonb,
'[[{"english":"A","thai":"เอ"},{"english":"is","thai":"อิส"},{"english":"for","thai":"ฟอร์"},{"english":"Apple.","thai":"แอปเปิล"}],[{"english":"B","thai":"บี"},{"english":"is","thai":"อิส"},{"english":"for","thai":"ฟอร์"},{"english":"Ball.","thai":"บอล"}],[{"english":"C","thai":"ซี"},{"english":"is","thai":"อิส"},{"english":"for","thai":"ฟอร์"},{"english":"Cat.","thai":"แคท"}],[{"english":"D","thai":"ดี"},{"english":"is","thai":"อิส"},{"english":"for","thai":"ฟอร์"},{"english":"Dog.","thai":"ด็อก"}],[{"english":"E","thai":"อี"},{"english":"is","thai":"อิส"},{"english":"for","thai":"ฟอร์"},{"english":"Egg.","thai":"เอ็ก"}],[{"english":"F","thai":"เอฟ"},{"english":"is","thai":"อิส"},{"english":"for","thai":"ฟอร์"},{"english":"Fish.","thai":"ฟิช"}],[{"english":"G","thai":"จี"},{"english":"is","thai":"อิส"},{"english":"for","thai":"ฟอร์"},{"english":"Gorilla.","thai":"กอริลลา"}]]'::jsonb,
'A คือ Apple B คือ Ball C คือ Cat D คือ Dog E คือ Egg F คือ Fish G คือ Gorilla','Colorful alphabet cards A-G with cute cartoon animals',
'[{"question":"ตัวอักษร A อ่านว่าอะไร?","options":["บี","ซี","เอ","ดี"],"correctIndex":2,"type":"vocab"},{"question":"Dog แปลว่าอะไร?","options":["แมว","ปลา","หมา","ไข่"],"correctIndex":2,"type":"vocab"},{"question":"คำว่า Fish เริ่มด้วยตัวอะไร?","options":["D","E","F","G"],"correctIndex":2,"type":"comprehension"},{"question":"ตัวอักษร E อ่านว่าอะไร?","options":["ดี","อี","เอฟ","บี"],"correctIndex":1,"type":"comprehension"}]'::jsonb,
true,'core-a0-alphabet','Letters A-G'),

(0,2,'Hat to Night','ตัวอักษร H-N',
'[{"word":"hat","phonetic":"แฮท","meaning":"หมวก","partOfSpeech":"n."},{"word":"ice","phonetic":"ไอซ์","meaning":"น้ำแข็ง","partOfSpeech":"n."},{"word":"juice","phonetic":"จูส","meaning":"น้ำผลไม้","partOfSpeech":"n."},{"word":"king","phonetic":"คิง","meaning":"กษัตริย์","partOfSpeech":"n."},{"word":"lion","phonetic":"ไลอัน","meaning":"สิงโต","partOfSpeech":"n."},{"word":"moon","phonetic":"มูน","meaning":"พระจันทร์","partOfSpeech":"n."},{"word":"night","phonetic":"ไนท์","meaning":"กลางคืน","partOfSpeech":"n."}]'::jsonb,
'[[{"english":"H","thai":"เอช"},{"english":"is","thai":"อิส"},{"english":"for","thai":"ฟอร์"},{"english":"Hat.","thai":"แฮท"}],[{"english":"I","thai":"ไอ"},{"english":"is","thai":"อิส"},{"english":"for","thai":"ฟอร์"},{"english":"Ice.","thai":"ไอซ์"}],[{"english":"J","thai":"เจ"},{"english":"is","thai":"อิส"},{"english":"for","thai":"ฟอร์"},{"english":"Juice.","thai":"จูส"}],[{"english":"K","thai":"เค"},{"english":"is","thai":"อิส"},{"english":"for","thai":"ฟอร์"},{"english":"King.","thai":"คิง"}],[{"english":"L","thai":"เอล"},{"english":"is","thai":"อิส"},{"english":"for","thai":"ฟอร์"},{"english":"Lion.","thai":"ไลอัน"}],[{"english":"M","thai":"เอม"},{"english":"is","thai":"อิส"},{"english":"for","thai":"ฟอร์"},{"english":"Moon.","thai":"มูน"}],[{"english":"N","thai":"เอน"},{"english":"is","thai":"อิส"},{"english":"for","thai":"ฟอร์"},{"english":"Night.","thai":"ไนท์"}]]'::jsonb,
'H คือ Hat I คือ Ice J คือ Juice K คือ King L คือ Lion M คือ Moon N คือ Night','Alphabet cards H-N with cartoon objects',
'[{"question":"Hat แปลว่าอะไร?","options":["รองเท้า","หมวก","เสื้อ","กระเป๋า"],"correctIndex":1,"type":"vocab"},{"question":"ตัวอักษร L อ่านว่า?","options":["เค","เอล","เอม","เอน"],"correctIndex":1,"type":"vocab"},{"question":"Moon แปลว่าอะไร?","options":["ดวงอาทิตย์","ดาว","พระจันทร์","เมฆ"],"correctIndex":2,"type":"comprehension"},{"question":"King เริ่มด้วยตัวอะไร?","options":["H","I","J","K"],"correctIndex":3,"type":"comprehension"}]'::jsonb,
true,'core-a0-alphabet','Letters H-N'),

(0,3,'Orange to Umbrella','ตัวอักษร O-U',
'[{"word":"orange","phonetic":"ออเรนจ์","meaning":"ส้ม","partOfSpeech":"n."},{"word":"pink","phonetic":"พิงค์","meaning":"สีชมพู","partOfSpeech":"adj."},{"word":"queen","phonetic":"ควีน","meaning":"ราชินี","partOfSpeech":"n."},{"word":"rain","phonetic":"เรน","meaning":"ฝน","partOfSpeech":"n."},{"word":"sun","phonetic":"ซัน","meaning":"ดวงอาทิตย์","partOfSpeech":"n."},{"word":"tree","phonetic":"ทรี","meaning":"ต้นไม้","partOfSpeech":"n."},{"word":"umbrella","phonetic":"อัมเบรลลา","meaning":"ร่ม","partOfSpeech":"n."}]'::jsonb,
'[[{"english":"O","thai":"โอ"},{"english":"is","thai":"อิส"},{"english":"for","thai":"ฟอร์"},{"english":"Orange.","thai":"ออเรนจ์"}],[{"english":"P","thai":"พี"},{"english":"is","thai":"อิส"},{"english":"for","thai":"ฟอร์"},{"english":"Pink.","thai":"พิงค์"}],[{"english":"Q","thai":"คิว"},{"english":"is","thai":"อิส"},{"english":"for","thai":"ฟอร์"},{"english":"Queen.","thai":"ควีน"}],[{"english":"R","thai":"อาร์"},{"english":"is","thai":"อิส"},{"english":"for","thai":"ฟอร์"},{"english":"Rain.","thai":"เรน"}],[{"english":"S","thai":"เอส"},{"english":"is","thai":"อิส"},{"english":"for","thai":"ฟอร์"},{"english":"Sun.","thai":"ซัน"}],[{"english":"T","thai":"ที"},{"english":"is","thai":"อิส"},{"english":"for","thai":"ฟอร์"},{"english":"Tree.","thai":"ทรี"}],[{"english":"U","thai":"ยู"},{"english":"is","thai":"อิส"},{"english":"for","thai":"ฟอร์"},{"english":"Umbrella.","thai":"อัมเบรลลา"}]]'::jsonb,
'O คือ Orange P คือ Pink Q คือ Queen R คือ Rain S คือ Sun T คือ Tree U คือ Umbrella','Alphabet cards O-U with cartoon objects',
'[{"question":"Orange แปลว่า?","options":["แอปเปิล","กล้วย","ส้ม","องุ่น"],"correctIndex":2,"type":"vocab"},{"question":"Queen แปลว่า?","options":["กษัตริย์","ราชินี","เจ้าชาย","เจ้าหญิง"],"correctIndex":1,"type":"vocab"},{"question":"ตัว S อ่านว่า?","options":["อาร์","เอส","ที","คิว"],"correctIndex":1,"type":"comprehension"},{"question":"Umbrella แปลว่า?","options":["หมวก","รองเท้า","ร่ม","กระเป๋า"],"correctIndex":2,"type":"comprehension"}]'::jsonb,
true,'core-a0-alphabet','Letters O-U'),

(0,4,'Van to Zebra','ตัวอักษร V-Z',
'[{"word":"van","phonetic":"แวน","meaning":"รถตู้","partOfSpeech":"n."},{"word":"water","phonetic":"วอเตอร์","meaning":"น้ำ","partOfSpeech":"n."},{"word":"x-ray","phonetic":"เอกซ์เรย์","meaning":"เอกซเรย์","partOfSpeech":"n."},{"word":"yellow","phonetic":"เยลโลว์","meaning":"สีเหลือง","partOfSpeech":"adj."},{"word":"zebra","phonetic":"ซีบรา","meaning":"ม้าลาย","partOfSpeech":"n."}]'::jsonb,
'[[{"english":"V","thai":"วี"},{"english":"is","thai":"อิส"},{"english":"for","thai":"ฟอร์"},{"english":"Van.","thai":"แวน"}],[{"english":"W","thai":"ดับเบิลยู"},{"english":"is","thai":"อิส"},{"english":"for","thai":"ฟอร์"},{"english":"Water.","thai":"วอเตอร์"}],[{"english":"X","thai":"เอกซ์"},{"english":"is","thai":"อิส"},{"english":"for","thai":"ฟอร์"},{"english":"X-ray.","thai":"เอกซ์เรย์"}],[{"english":"Y","thai":"วาย"},{"english":"is","thai":"อิส"},{"english":"for","thai":"ฟอร์"},{"english":"Yellow.","thai":"เยลโลว์"}],[{"english":"Z","thai":"ซี"},{"english":"is","thai":"อิส"},{"english":"for","thai":"ฟอร์"},{"english":"Zebra.","thai":"ซีบรา"}],[{"english":"Now","thai":"นาว"},{"english":"I","thai":"ไอ"},{"english":"know","thai":"โน"},{"english":"my","thai":"มาย"},{"english":"ABC!","thai":"เอบีซี!"}]]'::jsonb,
'V คือ Van W คือ Water X คือ X-ray Y คือ Yellow Z คือ Zebra ตอนนี้ฉันรู้จัก ABC แล้ว!','Alphabet cards V-Z with zebra cartoon',
'[{"question":"Zebra แปลว่า?","options":["สิงโต","ม้าลาย","ยีราฟ","ช้าง"],"correctIndex":1,"type":"vocab"},{"question":"ตัว W อ่านว่า?","options":["วี","ดับเบิลยู","เอกซ์","วาย"],"correctIndex":1,"type":"vocab"},{"question":"Yellow แปลว่าสีอะไร?","options":["แดง","น้ำเงิน","เขียว","เหลือง"],"correctIndex":3,"type":"comprehension"},{"question":"Van แปลว่า?","options":["รถยนต์","รถตู้","รถบัส","รถไฟ"],"correctIndex":1,"type":"comprehension"}]'::jsonb,
true,'core-a0-alphabet','Letters V-Z');
